### ISSUE TITLE
Mattermost API BindAddress crashes

### ISSUE THREAD

**Issue by InFerYes** [42wim/matterbridge#101]
### Which version of matterbridge are you using?
version 0.9.1-dev

### If you're having problems with mattermost please specify mattermost version. 
Version: 3.4.0

### Please describe the expected behavior.
Matterbridge should connect without error

#### Use logs from running ```matterbridge -debug``` if possible.
``` ./matterbridge -debug
INFO[2016-12-13T15:34:32+01:00] enabling debug
running version 0.9.1-dev
starting gateway "gateway_slack"
INFO[2016-12-13T15:34:32+01:00] Starting bridge: mattermost.bitstorm
INFO[2016-12-13T15:34:32+01:00] Connecting slackbot (team: bitstorm) on 127.0.0.1:8065  module=mattermost
DEBU[2016-12-13T15:34:32+01:00] trying login bitstorm slackbot 127.0.0.1:8065  module=matterclient
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x59e1d8]

goroutine 1 [running]:
panic(0x906600, 0xc4200100a0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/42wim/matterbridge/matterclient.(*MMClient).initUser(0xc4200857a0, 0x0, 0x0)
        /home/dennisf/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:626 +0x1e8
github.com/42wim/matterbridge/matterclient.(*MMClient).Login(0xc4200857a0, 0x99f724, 0x1e)
        /home/dennisf/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:149 +0x933
github.com/42wim/matterbridge/bridge/mattermost.(*Bmattermost).Connect(0xc42011f260, 0xc4201439b0, 0xc42010fca8)
        /home/dennisf/go/src/github.com/42wim/matterbridge/bridge/mattermost/mattermost.go:68 +0x27f
github.com/42wim/matterbridge/gateway.(*Gateway).AddBridge(0xc42004b5e0, 0xc42010fca8, 0x2, 0x2)
        /home/dennisf/go/src/github.com/42wim/matterbridge/gateway/gateway.go:43 +0x21d
github.com/42wim/matterbridge/gateway.(*Gateway).Start(0xc42004b5e0, 0x0, 0xc4201439b0)
        /home/dennisf/go/src/github.com/42wim/matterbridge/gateway/gateway.go:61 +0x1ff
main.main()
        /home/dennisf/go/src/github.com/42wim/matterbridge/matterbridge.go:53 +0x5ab
```

### Any steps to reproduce the behavior?
In the matterbridge.toml configuration, enable the mattermost API, set the BindAddress to 127.0.0.1:8065 or hostname.tld:8065 and this error occurs.

#### (be sure to exclude or anonymize private data (tokens/passwords))
```#This is configuration for matterbridge. TOML
###################################################################
#mattermost section
###################################################################
[mattermost]
#You can configure multiple servers "[mattermost.name]" or "[mattermost.name2]"
#In this example we use [mattermost.work]
#REQUIRED

[mattermost.bitstorm]
#### Settings for webhook matterbridge.
#### These settings will not be used when useAPI is enabled

#Url is your incoming webhook url as specified in mattermost.
#See account settings - integrations - incoming webhooks on mattermost.
#REQUIRED (unless useAPI=true)
URL="http://blabla"

#Address to listen on for outgoing webhook requests from mattermost.
#See account settings - integrations - outgoing webhooks on mattermost.
#This setting will not be used when using -plus switch which doesn't use
#webhooks
#REQUIRED (unless useAPI=true)
BindAddress="127.0.0.1:9999"

#Icon that will be showed in mattermost.
#OPTIONAL
IconURL="https://iconurl"

#### Settings for matterbridge -plus
#### Thse settings will only be used when using the -plus switch.

#### Settings for using matterbridge API
#OPTIONAL
useAPI=true

#The mattermost hostname.
#REQUIRED (when useAPI=true)
Server="127.0.0.1:8065"

#Your team on mattermost.
#REQUIRED (when useAPI=true)
Team="bitstorm"

#login/pass of your bot.
#Use a dedicated user for this and not your own!
#REQUIRED (when useAPI=true)
Login="slackbot"
Password="totallyasecret"

#Enable this to make a http connection (instead of https) to your mattermost.
#OPTIONAL (default false)
NoTLS=true

#### Shared settings for matterbridge and -plus

#Enable to not verify the certificate on your mattermost server.
#e.g. when using selfsigned certificates
#OPTIONAL (default false)
SkipTLSVerify=true

#how to format the list of IRC nicks when displayed in mattermost.
#Possible options are "table" and "plain"
#OPTIONAL (default plain)
NickFormatter="plain"
#How many nicks to list per row for formatters that support this.
#OPTIONAL (default 4)
NicksPerRow=4

#Whether to prefix messages from other bridges to mattermost with the sender's nick.
#Useful if username overrides for incoming webhooks isn't enabled on the
#mattermost server. If you set PrefixMessagesWithNick to true, each message
#from bridge to Mattermost will by default be prefixed by "bridge-" + nick. You can,
#however, modify how the messages appear, by setting (and modifying) RemoteNickFormat
#OPTIONAL (default false)
PrefixMessagesWithNick=false

#Nicks you want to ignore.
#Messages from those users will not be sent to other bridges.
#OPTIONAL
IgnoreNicks=""

#RemoteNickFormat defines how remote users appear on this bridge
#The string "{NICK}" (case sensitive) will be replaced by the actual nick / username.
#The string "{BRIDGE}" (case sensitive) will be replaced by the sending bridge
#The string "{PROTOCOL}" (case sensitive) will be replaced by the protocol used by the bridge
#OPTIONAL (default empty)
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

#Enable to show users joins/parts from other bridges (only from irc-bridge at the moment)
#OPTIONAL (default false)
ShowJoinPart=false
###################################################################
#slack section
###################################################################
[slack]

#You can configure multiple servers "[slack.name]" or "[slack.name2]"
#In this example we use [slack.hobby]
#REQUIRED
[slack.bitstormteam]
#### Settings for webhook matterbridge.
#### These settings will not be used when useAPI is enabled

#Url is your incoming webhook url as specified in slack
#See account settings - integrations - incoming webhooks on slack
#REQUIRED (unless useAPI=true)
URL="https://hooks.slack.com/blabla"

#Address to listen on for outgoing webhook requests from slack
#See account settings - integrations - outgoing webhooks on slack
#This setting will not be used when useAPI is eanbled
#webhooks
#REQUIRED (unless useAPI=true)
BindAddress="127.0.0.1:9999"

#### Settings for using slack API
#OPTIONAL
useAPI=true

#Token to connect with the Slack API
#You'll have to use a test/api-token using a dedicated user and not a bot token.
#See https://github.com/42wim/matterbridge/issues/75 for more info.
#REQUIRED (when useAPI=true)
Token="totallyasecret"

#### Shared settings for webhooks and API

#Icon that will be showed in slack
#The string "{NICK}" (case sensitive) will be replaced by the actual nick / username.
#The string "{BRIDGE}" (case sensitive) will be replaced by the sending bridge
#The string "{PROTOCOL}" (case sensitive) will be replaced by the protocol used by the bridge
#OPTIONAL
IconURL="https://robohash.org/{NICK}.png?size=48x48"

#how to format the list of IRC nicks when displayed in slack
#Possible options are "table" and "plain"
#OPTIONAL (default plain)
NickFormatter="plain"
#How many nicks to list per row for formatters that support this.
#OPTIONAL (default 4)
NicksPerRow=4

#Whether to prefix messages from other bridges to mattermost with RemoteNickFormat
#Useful if username overrides for incoming webhooks isn't enabled on the
#slack server. If you set PrefixMessagesWithNick to true, each message
#from bridge to Slack will by default be prefixed by "bridge-" + nick. You can,
#however, modify how the messages appear, by setting (and modifying) RemoteNickFormat
#OPTIONAL (default false)
PrefixMessagesWithNick=false

#Nicks you want to ignore.
#Messages from those users will not be sent to other bridges.
#OPTIONAL
IgnoreNicks=""

#RemoteNickFormat defines how remote users appear on this bridge
#The string "{NICK}" (case sensitive) will be replaced by the actual nick / username.
#The string "{BRIDGE}" (case sensitive) will be replaced by the sending bridge
#The string "{PROTOCOL}" (case sensitive) will be replaced by the protocol used by the bridge
#OPTIONAL (default empty)
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

#Enable to show users joins/parts from other bridges (only from irc-bridge at the moment)
#OPTIONAL (default false)
ShowJoinPart=false

###################################################################
#Gateway configuration
###################################################################

#You can specify multiple gateways using [[gateway]]
#Each gateway has a [[gateway.in]] and a [[gateway.out]]
#[[gateway.in]] specifies the account and channels we will receive messages from.
#[[gateway.out]] specifies the account and channels we will send the messages
#from [[gateway.in]] to.
#
#Most of the time [[gateway.in]] and [[gateway.out]] are the same if you
#want bidirectional bridging. You can then use [[gateway.inout]]
#

[[gateway]]
#OPTIONAL (not used for now)
name="gateway_slack"
#Enable enables this gateway
##OPTIONAL (default false)
enable=true

    #[[gateway.inout]] can be used when then channel will be used to receive from
    #and send messages to
    [[gateway.inout]]
    account="mattermost.bitstorm"
    channel="mattermost"

    [[gateway.inout]]
    account="slack.bitstormteam"
    channel="mattermost"


#If you want to do a 1:1 mapping between protocols where the channelnames are the same
#e.g. slack and mattermost you can use the samechannelgateway configuration
#the example configuration below send messages from channel testing on mattermost to
#channel testing on slack and vice versa. (and for the channel testing2 and testing3)

[[samechannelgateway]]
   enable = false
   accounts = [ "mattermost.bitstorm","slack.bitstormteam" ]
   channels = [ "mattermost"]
```

**Comment by InFerYes** [comment]
When I prepend **http://** to example.tld:8065 then I get this:

```INFO[2016-12-13T15:31:11+01:00] enabling debug
running version 0.9.1-dev
starting gateway "gateway_slack"
INFO[2016-12-13T15:31:11+01:00] Starting bridge: mattermost.bitstorm
INFO[2016-12-13T15:31:11+01:00] Connecting slackbot (team: bitstorm) on http://example.tld:8065  module=mattermost
DEBU[2016-12-13T15:31:11+01:00] trying login bitstorm slackbot http://example.tld:8065  module=matterclient
DEBU[2016-12-13T15:31:11+01:00] Post http://http//example.tld:8065/api/v3/users/login: dial tcp: lookup http on 213.187.34.100:53: no such host  module=matterclient
FATA[2016-12-13T15:31:11+01:00] starting gateway failed &errors.errorString{s:"Bridge mattermost.bitstorm failed to start: model.client.connecting.app_error"}
```

**Comment by 42wim** [comment]
As specified in the README on the main page:
You can not use matterbridge 0.9.x with mattermost 3.4.0 , you'll need to upgrade to mattermost 3.5.x
You'll have to use matterbridge 0.7.1 for mattermost 3.4.0

If you are using matterbridge 0.9.x and mattermost 3.5.x you can use following config

```
[mattermost]
[mattermost.bitstorm]
useAPI=true
Server="127.0.0.1:8065"
Team="bitstorm"
Login="slackbot"
Password="totallyasecret"
NoTLS=true

PrefixMessagesWithNick=false
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
ShowJoinPart=false

[slack]
[slack.bitstormteam]
useAPI=true
Token="totallyasecret"
PrefixMessagesWithNick=false
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
ShowJoinPart=false

[[gateway]]
enable=true

    [[gateway.inout]]
    account="mattermost.bitstorm"
    channel="mattermost"

    [[gateway.inout]]
    account="slack.bitstormteam"
    channel="mattermost"
```

If you use matterbridge 0.7.1 and mattermost 3.4.0 you can use the following config

```
[mattermost]
[mattermost.bitstorm]
useAPI=true
Server="127.0.0.1:8065"
Team="bitstorm"
Login="slackbot"
Password="totallyasecret"
NoTLS=true

PrefixMessagesWithNick=false
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
ShowJoinPart=false

[slack]
[slack.bitstormteam]
useAPI=true
Token="totallyasecret"
PrefixMessagesWithNick=false
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
ShowJoinPart=false

[[gateway]]
enable=true

    [[gateway.in]]
    account="mattermost.bitstorm"
    channel="mattermost"

    [[gateway.out]]
    account="mattermost.bitstorm"
    channel="mattermost"

    [[gateway.in]]
    account="slack.bitstormteam"
    channel="mattermost"

    [[gateway.out]]
    account="slack.bitstormteam"
    channel="mattermost"
```

**Comment by InFerYes** [comment]
Mea culpa. 

I have upgraded Mattermost to 3.5.1 now and I've used your first config. No more crash when using the api on Mattermost.
