### ISSUE TITLE
Nullpointer when using webhooks

### ISSUE THREAD

**Issue by SMillerDev** [42wim/matterbridge#110]
Please answer the following questions. 

### Which version of matterbridge are you using?
0.9.0

### If you're having problems with mattermost please specify mattermost version. 
3.5.1

### Please describe the expected behavior.
Slack webhook messages are recieved and relayed to the mattermost bridge and the other way around.

#### Use logs from running ```matterbridge -debug``` if possible.
A nullpointer is thrown here
https://github.com/42wim/matterbridge/blob/master/bridge/slack/slack.go#L162

because there is no username defined with webhooks

```
DEBU[2017-01-11T14:00:25+01:00] receiving from matterhook (slack) matterhook.IMessage{BotID:"", BotName:"", Token:"<token>", TeamID:"<ID>", TeamDomain:"<domain>", ChannelID:"<Channel>", ChannelName:"<name>", Timestamp:"1484139625.000025", UserID:"U0BDH8N0J", UserName:"sean", PostId:"", RawText:"", ServiceId:"<ID>", Text:"test", TriggerWord:""}  module=slack
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x522d95]

goroutine 9 [running]:
panic(0x903240, 0xc42000e120)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/42wim/matterbridge/bridge/slack.(*Bslack).handleSlack(0xc42007d400)
        /go/src/github.com/42wim/matterbridge/bridge/slack/slack.go:162 +0x255
created by github.com/42wim/matterbridge/bridge/slack.(*Bslack).Connect
        /go/src/github.com/42wim/matterbridge/bridge/slack/slack.go:64 +0x278
```

### Any steps to reproduce the behavior?
setup a slack-mattermost link using just webhooks

#### (be sure to exclude or anonymize private data (tokens/passwords))

```
[slack]
[slack.company]
    URL="<URL>"
    BindAddress="0.0.0.0:9000"
    PrefixMessagesWithNick=true
[mattermost]
[mattermost.company]
    BindAddress                       = "0.0.0.0:9998"
    URL                                     = "<URL>"
    PrefixMessagesWithNick=true
[[gateway]]
    enable    = true
[[gateway.inout]]
    account  = "mattermost.company"
    channel  = "off-topic"

[[gateway.inout]]
    account  = "slack.company"
    channel  = "#mmtesting"
```

**Comment by 42wim** [comment]
Thanks for reporting!  
Fixed in master, could you test ?

**Comment by SMillerDev** [comment]
It's now one way traffic, mattermost can send to slack but slack can't send to mattermost.
From what I could see from your code, it might need a webhook user defined instead of only checking for the user when api is used.

**Comment by 42wim** [comment]
I just set up a test-setup, works fine for me. 
Could you run matterbridge with ```-debug``` sent a message from slack to mattermost and one from mattermost to slack and paste output ? (filtered for private data)

**Comment by SMillerDev** [comment]
```root@moltres:/opt/matterbridge# ./matterbridge -debug
INFO[2017-01-18T12:16:22+01:00] enabling debug                               
running version 0.9.1-dev
starting gateway "gateway2"
INFO[2017-01-18T12:16:22+01:00] Starting bridge: slack.company               
INFO[2017-01-18T12:16:22+01:00] Connecting                                    module=slack
INFO[2017-01-18T12:16:22+01:00] Connection succeeded                          module=slack
INFO[2017-01-18T12:16:22+01:00] slack.company: joining #mmtesting            
INFO[2017-01-18T12:16:22+01:00] Starting bridge: mattermost.company          
INFO[2017-01-18T12:16:22+01:00] Connecting webhooks                           module=mattermost
INFO[2017-01-18T12:16:22+01:00] mattermost.company: joining off-topic        
2017/01/18 12:16:22 Listening on http://0.0.0.0:9000...
DEBU[2017-01-18T12:16:22+01:00] Choosing API based slack connection: false    module=slack
2017/01/18 12:16:22 Listening on http://0.0.0.0:9998...
DEBU[2017-01-18T12:16:22+01:00] Choosing API based Mattermost connection: false  module=mattermost
DEBU[2017-01-18T12:16:23+01:00] Start listening for Slack messages            module=slack
DEBU[2017-01-18T12:18:47+01:00] receiving from matterhook (slack) matterhook.IMessage{BotID:"", BotName:"", Token:"TOKEN", TeamID:"ID", TeamDomain:"m2mobi", ChannelID:"ID", ChannelName:"mmtesting", Timestamp:"1484738326.000040", UserID:"ID", UserName:"sean", PostId:"", RawText:"", ServiceId:"ID", Text:"**test**", TriggerWord:""}  module=slack
DEBU[2017-01-18T12:18:47+01:00] Sending message from sean on slack.company to gateway  module=slack


EBU[2017-01-18T12:19:46+01:00] Receiving from matterhook matterhook.IMessage{BotID:"", BotName:"", Token:"TOKEN", TeamID:"ID", TeamDomain:"m2mobi", ChannelID:"ID", ChannelName:"off-topic", Timestamp:"1484738386", UserID:"ID", UserName:"smillernl", PostId:"ID", RawText:"", ServiceId:"", Text:"**and back**", TriggerWord:"and"}  module=mattermost
DEBU[2017-01-18T12:19:46+01:00] Sending message from smillernl on mattermost.company to gateway  module=mattermost
DEBU[2017-01-18T12:19:46+01:00] Sending config.Message{Text:"**and back**", Channel:"#mmtesting", Username:"smillernl", Avatar:"", Account:"mattermost.company", Event:""} from mattermost.company (off-topic) to slack.company (#mmtesting) 
DEBU[2017-01-18T12:19:46+01:00] Receiving config.Message{Text:"**and back**", Channel:"#mmtesting", Username:"", Avatar:"", Account:"mattermost.company", Event:""}  module=slack
DEBU[2017-01-18T12:19:46+01:00] receiving from matterhook (slack) matterhook.IMessage{BotID:"ID", BotName:"mattermost-webhook", Token:"TOKEN", TeamID:"ID", TeamDomain:"m2mobi", ChannelID:"ID", ChannelName:"mmtesting", Timestamp:"1484738386.000041", UserID:"USLACKBOT", UserName:"slackbot", PostId:"", RawText:"", ServiceId:"ID", Text:"**and back**", TriggerWord:""}  module=slack
DEBU[2017-01-18T12:19:46+01:00] Sending message from slackbot on slack.company to gateway  module=slack
```

**Comment by 42wim** [comment]
The issue is probably the slack channel name, you must remove the "#" in your config.

```
[[gateway.inout]]
    account  = "slack.company"
    channel  = "mmtesting"
```

**Comment by SMillerDev** [comment]
I'm an idiot, works now. Thanks
