### ISSUE TITLE
Slack segfaults with `WebhookBindAddress`

### ISSUE THREAD

**Issue by kousu** [42wim/matterbridge#1123]
**Describe the bug**
The Slack gateway crashes with

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x55b783a8afb5]
```

when I have `WebhookBindAddress` defined. Unfortunately the default config file shipped on my system had it defined (though with a warning above it that I shouldn't use it).

**To Reproduce**

1. Follow https://github.com/42wim/matterbridge/wiki/Slack-bot-setup#bot-based-setup
2. `/invite` the bot to you Slack's "#general".
2. Copy the "Bot User OAuth Access Token" from https://api.slack.com/apps/A012E7E2L7R/oauth?success=1
3. Use this config file, pasting in the Slack token:

```
# matterbridge.toml 
[slack]
[slack.lab]
Token="xoxb-XXXXXXXXXXXXXXX" # token here

#Debug=true

#WebhookURL="https://hooks.slack.com/services/yourhook"
WebhookBindAddress="0.0.0.0:9999"

[[gateway]]
name="gw"
enable=true
    
    [[gateway.inout]]
    account="slack.lab"
    channel="general"
```
4. `matterbridge -debug -conf matterbridge.toml`

**Expected behavior**

Connect to Slack and relay messages :)

**Screenshots/debug logs**

```
$ matterbridge -debug -conf matterbridge.toml 
[0000]  INFO main:         Enabling debug logging.
[0000]  INFO main:         Running version 1.17.4 
[0000]  INFO router:       Parsing gateway gw
[0000]  INFO router:       Starting bridge: slack.lab 
[0000]  INFO slack:        Connecting using token
[0000]  INFO slack:        slack.lab: joining general (ID: generalslack.lab)
[0000] DEBUG slack:        Choosing webhooks based receiving
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x55ac18053fb5]

goroutine 15 [running]:
github.com/42wim/matterbridge/matterhook.(*Client).Receive(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/42wim/matterbridge/matterhook/matterhook.go:143 +0x75
github.com/42wim/matterbridge/bridge/slack.(*Bslack).handleMatterHook(0xc0000e2e80, 0xc000089680)
	github.com/42wim/matterbridge/bridge/slack/handlers.go:106 +0x49
created by github.com/42wim/matterbridge/bridge/slack.(*Bslack).handleSlack
	github.com/42wim/matterbridge/bridge/slack/handlers.go:21 +0x108
```

If I turn on `Debug="true"`:

```
$ matterbridge -debug -conf matterbridge.toml 
[0000]  INFO main:         Enabling debug logging.
[0000]  INFO main:         Running version 1.17.4 
[0000]  INFO router:       Parsing gateway gw
[0000]  INFO router:       Starting bridge: slack.lab 
[0000]  INFO slack:        Connecting using token
[0000]  INFO slack:        slack.lab: joining general (ID: generalslack.lab)
slack-go/slack2020/04/30 19:45:55 websocket_managed_conn.go:177: Connecting to RTM
[0000] DEBUG slack:        Choosing webhooks based receiving
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x560e9fa0efb5]

goroutine 15 [running]:
github.com/42wim/matterbridge/matterhook.(*Client).Receive(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/42wim/matterbridge/matterhook/matterhook.go:143 +0x75
github.com/42wim/matterbridge/bridge/slack.(*Bslack).handleMatterHook(0xc0000e2e80, 0xc000089620)
	github.com/42wim/matterbridge/bridge/slack/handlers.go:106 +0x49
created by github.com/42wim/matterbridge/bridge/slack.(*Bslack).handleSlack
	github.com/42wim/matterbridge/bridge/slack/handlers.go:21 +0x108
```

If I comment out `WebhookBindAddress` it works:

```
$ matterbridge -debug -conf matterbridge.toml 
[0000]  INFO main:         Enabling debug logging.
[0000]  INFO main:         Running version 1.17.4 
[0000]  INFO router:       Parsing gateway gw
[0000]  INFO router:       Starting bridge: slack.lab 
[0000]  INFO slack:        Connecting using token
[0000]  INFO slack:        slack.lab: joining general (ID: generalslack.lab)
slack-go/slack2020/04/30 19:46:38 websocket_managed_conn.go:177: Connecting to RTM
[0000] DEBUG slack:        Choosing token based receiving
[0000] DEBUG slack:        == Receiving event &slack.ConnectingEvent{Attempt:1, ConnectionCount:0}
[0000]  INFO main:         Gateway(s) started succesfully. Now relaying messages
slack-go/slack2020/04/30 19:46:38 rtm.go:71: Using URL: wss://cerberus-xxxx.lb.slack-msgs.com/websocket/t_UJWoGVkR1guFSdIrSuuxQ_I0AZkqtyfXpIlP7SGt9AIvj7kEH3mrRTcthbTFaIKCQg1o-tO3D0BLa5iezvW4mnFOxu0atoXDoxKWZ_5Yxr2BurKCoG6TN08mnLfcd4
slack-go/slack2020/04/30 19:46:38 websocket_managed_conn.go:193: Dialing to websocket on url wss://cerberus-xxxx.lb.slack-msgs.com/websocket/t_UJWoGVkR1guFSdIrSuuxQ_I0AZkqtyfXpIlP7SGt9AIvj7kEH3mrRTcthbTFaIKCQg1o-tO3D0BLa5iezvW4mnFOxu0atoXDoxKWZ_5Yxr2BurKCoG6TN08mnLfcd4
slack-go/slack2020/04/30 19:46:38 websocket_managed_conn.go:59: RTM connection succeeded on try 0
[0000] DEBUG slack:        == Receiving event &slack.ConnectedEvent{ConnectionCount:0, Info:(*slack.Info)(0xc0001f5c40)}
slack-go/slack2020/04/30 19:46:38 websocket_managed_conn.go:383: Incoming Event: {"type": "hello"}
slack-go/slack2020/04/30 19:46:38 users.go:331: GetUsersContext: got 3 users; metadata {}
[0001] DEBUG slack:        Start listening for Slack messages
[0001] DEBUG slack:        getting 3 users
```

**Environment (please complete the following information):**
 - OS: ArchLinux
 - Matterbridge version: version: 1.17.4 
- installed from pacman:

```
$ pacman -Qi matterbridge
Name            : matterbridge
Version         : 1.17.4-1
Description     : Multi-protocols (IRC/XMPP/Mattermost/Slack/Matrix/etc) bridge
Architecture    : x86_64
URL             : https://github.com/42wim/matterbridge
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : glibc
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 59.70 MiB
Packager        : Bruno Pagani <archange@archlinux.org>
Build Date      : Wed 22 Apr 2020 05:00:23 PM CEST
Install Date    : Sun 26 Apr 2020 12:00:49 AM CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by kousu** [comment]
There's a similar crash that happens once you try to relay a message if the config contains:

```
WebhookURL="https://hooks.slack.com/services/yourhook"
```

```
[0019] DEBUG slack:        => Receiving config.Message{Text:"test", Channel:"general", Username:"[discord] <kousu> ", UserID:"xxxxxxxxxxxxxxxxx", Avatar:"https://cdn.discordapp.com/......", Account:"discord.discontentslab", Event:"", Protocol:"discord", Gateway:"gw", ParentID:"", Timestamp:time.Time{wall:0xbfa2e1c691a43969, ext:19429094526, loc:(*time.Location)(0x561760f7e4c0)}, ID:"", Extra:map[string][]interface {}(nil)}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x56175eb141cc]

goroutine 372 [running]:
github.com/42wim/matterbridge/matterhook.(*Client).Send(0x0, 0xc000418876, 0x7, 0xc0004347c0, 0x3a, 0x0, 0x0, 0xc0003465a0, 0x12, 0xc000605a30, ...)
	github.com/42wim/matterbridge/matterhook/matterhook.go:155 +0x12c
github.com/42wim/matterbridge/bridge/slack.(*Bslack).sendWebhook(0xc0000e5500, 0xc000605a30, 0x4, 0xc000418876, 0x7, 0xc0003465a0, 0x12, 0xc0006260e0, 0x12, 0xc0004347c0, ...)
	github.com/42wim/matterbridge/bridge/slack/slack.go:270 +0x384
github.com/42wim/matterbridge/bridge/slack.(*Bslack).Send(0xc0000e5500, 0xc000605a30, 0x4, 0xc000418876, 0x7, 0xc0003465a0, 0x12, 0xc0006260e0, 0x12, 0xc0004347c0, ...)
	github.com/42wim/matterbridge/bridge/slack/slack.go:208 +0x240
github.com/42wim/matterbridge/gateway.(*Gateway).SendMessage(0xc0000769c0, 0xc0000f5520, 0xc0000e5480, 0xc000320e80, 0x0, 0x0, 0xe, 0xc000379720, 0x14, 0xc000379720)
	github.com/42wim/matterbridge/gateway/gateway.go:457 +0x6af
github.com/42wim/matterbridge/gateway.(*Gateway).handleMessage(0xc0000769c0, 0xc0000f5520, 0xc0000e5480, 0x0, 0x0, 0x0)
	github.com/42wim/matterbridge/gateway/handlers.go:226 +0x25c
github.com/42wim/matterbridge/gateway.(*Router).handleReceive(0xc0000805a0)
	github.com/42wim/matterbridge/gateway/router.go:152 +0x243
created by github.com/42wim/matterbridge/gateway.(*Router).Start
	github.com/42wim/matterbridge/gateway/router.go:102 +0x939
```

Commenting out `WebhookURL` fixes it.

**Comment by kousu** [comment]
And as always, thanks for making such useful software. Matterbridge is _so key_.

**Comment by kousu** [comment]
Maybe the thing to do is to make sure distros don't ship the Webhook settings at all? Probably what's happening is the token I gave doesn't have webhook permissions (because it's a Bot User Token) and matterbridge is choking on something it gets from the Slack API.

**Comment by 42wim** [comment]
Thanks for reporting and debugging!
This crash should be fixed now in master.
