### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by elimisteve** [42wim/matterbridge#113]
Please answer the following questions. 

### Which version of matterbridge are you using?

version: 0.9.1-dev

### If you're having problems with mattermost please specify mattermost version. 

Version: 3.5.0  (3.5.1)
Database: mysql

Build Hash: 36f62c9e82350f58c902f64a5d3304872431ad41
EE Build Hash: 3b20048146103a81f7df91c7a6ae077f2c062b34

### Please describe the expected behavior.

matterbridge should keep working as a bridge without panicking :-)

### Please describe the actual behavior. 

It panics:

```
...
DEBU[2017-01-16T06:27:49-05:00] WsReceiver: model.WebSocketEvent{Event:"status_change", Data:map[string]interface {}{"status":"online", "user_id":"9b4zzzdmkjghfmmiq6jibaajxh"}, Broadcast:(*model.WebsocketBroadcast)(0xc424bacc40), PreComputeJson:[]uint8(nil)}  module=matterclient
DEBU[2017-01-16T06:28:33-05:00] PING/PONG                                     module=irc
DEBU[2017-01-16T06:28:33-05:00] "PING :wilhelm.freenode.net"                  module=irc
DEBU[2017-01-16T06:30:38-05:00] PING/PONG                                     module=irc
DEBU[2017-01-16T06:30:38-05:00] "PING :wilhelm.freenode.net"                  module=irc
ERRO[2017-01-16T06:30:49-05:00] error:websocket: close 1006 (abnormal closure): unexpected EOF  module=matterclient
DEBU[2017-01-16T06:30:49-05:00] trying login community swborders_bridge chat.securitywithoutborders.org  module=matterclient
DEBU[2017-01-16T06:30:51-05:00] initUser(): found our team community (id: w6gkfje937nt3kxaet61immfcw)  module=matterclient
DEBU[2017-01-16T06:30:51-05:00] WsClient: making connection                   module=matterclient
DEBU[2017-01-16T06:30:51-05:00] WsReceiver: model.WebSocketEvent{Event:"hello", Data:map[string]interface {}{"server_version":"3.5.0.3.5.1.d6c92c155a5f25afd9a43b29266fcf05"}, Broadcast:(*model.WebsocketBroadcast)(0xc424bacb80), PreComputeJson:[]uint8(nil)}  module=matterclient
DEBU[2017-01-16T06:30:51-05:00] WsReceiver: model.WebSocketEvent{Event:"status_change", Data:map[string]interface {}{"user_id":"9b4zzzdmkjghfmmiq6jibaajxh", "status":"online"}, Broadcast:(*model.WebsocketBroadcast)(0xc424bacd00), PreComputeJson:[]uint8(nil)}  module=matterclient
ERRO[2017-01-16T06:31:51-05:00] error:websocket: close 1006 (abnormal closure): unexpected EOF  module=matterclient
DEBU[2017-01-16T06:31:51-05:00] trying login community swborders_bridge chat.securitywithoutborders.org  module=matterclient
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x59eac3]

goroutine 55 [running]:
panic(0x906800, 0xc4200100c0)
        /home/ubuntu/go/src/runtime/panic.go:500 +0x1a1
github.com/42wim/matterbridge/matterclient.(*MMClient).initUser(0xc42015c750, 0x0, 0x0)
        /home/ubuntu/gocode/src/github.com/42wim/matterbridge/matterclient/matterclient.go:628 +0x263
github.com/42wim/matterbridge/matterclient.(*MMClient).Login(0xc42015c750, 0xc424c9bee0, 0x2)
        /home/ubuntu/gocode/src/github.com/42wim/matterbridge/matterclient/matterclient.go:149 +0x933
github.com/42wim/matterbridge/matterclient.(*MMClient).WsReceiver(0xc42015c750)
        /home/ubuntu/gocode/src/github.com/42wim/matterbridge/matterclient/matterclient.go:217 +0x7ba
created by github.com/42wim/matterbridge/bridge/mattermost.(*Bmattermost).Connect
        /home/ubuntu/gocode/src/github.com/42wim/matterbridge/bridge/mattermost/mattermost.go:74 +0x36e
```

### Any steps to reproduce the behavior?

Don't know; just kept it running for a while.

### Please add your configuration file

```
[irc]
    [irc.freenode]
    Server="irc.freenode.net:6667"
    Nick="swb_bridge"
    RemoteNickFormat="<{NICK}> "

[mattermost]
    [mattermost.work]
    useAPI=true
    Server="chat.securitywithoutborders.org"
    Team="community"
    Login="swborders_bridge"
    Password="..."
    PrefixMessagesWithNick=true
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="gateway1"
enable=true
    [[gateway.in]]
    account="irc.freenode"
    channel="#securitywithoutborders"

    [[gateway.out]]
    account="irc.freenode"
    channel="#securitywithoutborders"

    [[gateway.in]]
    account="mattermost.work"
    channel="town-square"
    
    [[gateway.out]]
    account="mattermost.work"
    channel="town-square"
```

**Comment by 42wim** [comment]
Please upgrade to 0.9.1 release (or current master), that crash should be handled.
Feel free to reopen this if it happens again.
