### ISSUE TITLE
whatsapp: some errors

### ISSUE THREAD

**Issue by supmyhava** [42wim/matterbridge#1243]
i got some error while using matterbrige with IRC to whatsapp

[94022] ERROR gateway:      SendMessage failed: sending message timed out
[94394] ERROR whatsapp:     Connection failed, underlying error: connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpected EOF
[94394]  INFO whatsapp:     Waiting 1s...
[94395]  INFO whatsapp:     Reconnecting...
[99421] ERROR whatsapp:     Connection failed, underlying error: connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpected EOF
[99421]  INFO whatsapp:     Waiting 1s...
[99422]  INFO whatsapp:     Reconnecting...
[99433] ERROR whatsapp:     keepAlive failed: connection timed out
[105229] ERROR whatsapp:     Connection failed, underlying error: connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpected EOF
[105229]  INFO whatsapp:     Waiting 1s...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x16e53b6]

goroutine 193276 [running]:
github.com/Rhymen/go-whatsapp.(*Conn).Disconnect(0xc000128100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200818115958-f07a700b9819/conn.go:212 +0x96
github.com/Rhymen/go-whatsapp.(*Conn).readPump.func1(0xc000128100)
        /go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.1.1-0.20200818115958-f07a700b9819/read.go:21 +0x65

after a few hours the bot is Disconnects with those errors

**Comment by 42wim** [comment]
Seems like an internet connection issue

**Comment by supmyhava** [comment]
> Seems like an internet connection/network issue

ohhh ok i will check it 
thank you.
