### ISSUE TITLE
Matrix bridge doesn't work

### ISSUE THREAD

**Issue by AnotherBugworm** [42wim/matterbridge#132]
Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
`version: 0.9.3 cd0a2be`
`version: 0.10.0-dev `

### Please describe the expected behavior.
It should login and work

### Please describe the actual behavior. 
Errors, different for release and git versions

#### Use logs from running ```matterbridge -debug``` if possible.
version: 0.9.3 cd0a2be:
```
INFO[2017-03-13T12:33:57+02:00] Enabling debug                               
INFO[2017-03-13T12:33:57+02:00] Running version 0.9.3 cd0a2be                
INFO[2017-03-13T12:33:57+02:00] Starting gateway "mygateway"                 
INFO[2017-03-13T12:33:57+02:00] Starting bridge: matrix.bridge               
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x91b71e]

goroutine 1 [running]:
github.com/42wim/matterbridge/gateway.(*Gateway).AddBridge(0xc4200a1090, 0xc420151d28, 0x3, 0x3)
        /go/src/github.com/42wim/matterbridge/gateway/gateway.go:47 +0x21e
github.com/42wim/matterbridge/gateway.(*Gateway).Start(0xc4200a1090, 0xc42008cd20, 0xc4200a1090)
        /go/src/github.com/42wim/matterbridge/gateway/gateway.go:68 +0x226
main.main()
        /go/src/github.com/42wim/matterbridge/matterbridge.go:55 +0x465
```

version: 0.10.0-dev:
```
INFO[2017-03-13T12:33:04+02:00] Enabling debug                               
INFO[2017-03-13T12:33:04+02:00] Running version 0.10.0-dev                   
INFO[2017-03-13T12:33:04+02:00] Starting gateway "mygateway"                 
INFO[2017-03-13T12:33:04+02:00] Starting bridge: matrix.bridge               
INFO[2017-03-13T12:33:04+02:00] Connecting                                    module=matrix
DEBU[2017-03-13T12:33:04+02:00] &url.Error{Op:"Post", URL:"/_matrix/client/r0/login", Err:(*http.badStringError)(0xc420169b60)}  module=matrix
FATA[2017-03-13T12:33:04+02:00] Starting gateway failed &errors.errorString{s:"Bridge matrix.bridge failed to start: Post /_matrix/client/r0/login: unsupported protocol scheme \"\""} 
```

### Please add your configuration file 
```
[telegram]
        [telegram.bridge]
        Token="mytoken"
        RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[matrix]
        [matrix.bridge]
        URL="https://matrix.org"
        Login="Bridge" #also tried @Bridge:matrix.org
        Password="mypass"

[discord]
        [discord.test]
        Token="mytoken"
        Server="[RU] Borderlands Community"
        RemoteNickFormat="**[{PROTOCOL}] <{NICK}>** "

[[gateway]]
name="mygateway"
enable=true
        [[gateway.inout]]
        account="matrix.bridge"
        channel="#that_is_linux:matrix.org"

        [[gateway.inout]]
        account="telegram.bridge"
        channel="-1001065669628"
        
        [[gateway.inout]]
        account="discord.test"
        channel="test_room_tlach"
```

**Comment by 42wim** [comment]
matrix support only works in 0.10.0-dev

Seems like I made a mistake in my matrix sample config
```URL``` should be ```Server```

The following snippet should work
```
[matrix]
        [matrix.bridge]
        server="https://matrix.org"
        login="Bridge"
        password="mypass"
```

**Comment by AnotherBugworm** [comment]
now it works, thanks
