### ISSUE TITLE
lottie errors out on start

### ISSUE THREAD

**Issue by computeronix** [42wim/matterbridge#1477]
**Describe the bug**
during startup i receive the following error

[0000]  INFO main:         Running version 1.22.1 b979aff2
2021/05/18 03:28:04 Telegram bridge configured to convert .tgs files to 'png', but lottie does not appear to work:
&exec.ExitError{ProcessState:(*os.ProcessState)(0xc00001e648), Stderr:[]uint8(nil)}

**To Reproduce**
In Azure, setup an Ubuntu 18.04.5 LTS VM
Download latest version of matterbridge
setup matterbridge config to include
MediaConvertWebPToPNG=true
MediaConvertTgs="png"

Install dependencies: pip3 install lottie cairosvg

**Expected behavior**
Matterbridge should run after above dependencies have been installed

**Screenshots/debug logs**
**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1047-azure x86_64)
 - Matterbridge version: 1.22.1 b979aff2

**Comment by 42wim** [comment]
Is the `lottie_convert.py` script reachable in the PATH matterbridge is using?
Try `lottie_convert.py --help`

**Comment by computeronix** [comment]
Thank you so much for this as this helped point me in the right direction.

When I ran 

lottie_convert.py --help

I received:

Traceback (most recent call last):
  File "/usr/local/bin/lottie_convert.py", line 11, in <module>
    from lottie.exporters import exporters
  File "/usr/local/lib/python3.9/dist-packages/lottie/__init__.py", line 3, in <                                                                                                                                                             module>
    from . import objects, parsers, utils, exporters, nvector, importers
  File "/usr/local/lib/python3.9/dist-packages/lottie/exporters/__init__.py", li                                                                                                                                                             ne 16, in <module>
    from . import cairo, gif
  File "/usr/local/lib/python3.9/dist-packages/lottie/exporters/cairo.py", line                                                                                                                                                              1, in <module>
    import cairosvg
  File "/usr/local/lib/python3.9/dist-packages/cairosvg/__init__.py", line 26, i                                                                                                                                                             n <module>
    from . import surface  # noqa isort:skip
  File "/usr/local/lib/python3.9/dist-packages/cairosvg/surface.py", line 9, in                                                                                                                                                              <module>
    import cairocffi as cairo
  File "/usr/local/lib/python3.9/dist-packages/cairocffi/__init__.py", line 48,                                                                                                                                                              in <module>
    cairo = dlopen(
  File "/usr/local/lib/python3.9/dist-packages/cairocffi/__init__.py", line 45,                                                                                                                                                              in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': libcairo.so.2: cannot open shared object fi                                                                                                                                                             le: No such file or directory
cannot load library 'libcairo.2.dylib': libcairo.2.dylib: cannot open shared obj                                                                                                                                                             ect file: No such file or directory
cannot load library 'libcairo-2.dll': libcairo-2.dll: cannot open shared object                                                                                                                                                              file: No such file or directory


Digging into this message, I found the following package was needed to be installed:
sudo apt-get install libcairo2-dev

Now the lottie_convert.py --help returns the help menu.

Next I attempted to run matterbridge and it ran successfully with the parameters for Web PNG and then converted the stickers properly.

I would recommend adding this to https://github.com/42wim/matterbridge/pull/1173 as part of a recommendation if users run into this.

Thank you!
