### ISSUE TITLE
Issue with Discord to Discord bridging

### ISSUE THREAD

**Issue by geleeroyale** [42wim/matterbridge#1513]
**Describe the bug**
Almost a year ago I started bridging betweend different discord community servers. It is quite a popular service, but all of a sudden it is not working anymore. I also bridge between telegram and matrix servers to discord and those work fine. I think it is something that Discord changed.

**To Reproduce**
Make a gateway-in-out and reference different discord servers

**Expected behavior**
All messages get bridged.

**Screenshots/debug logs**
Usually the bridge runs fine, however when I tried last it crashed with this error - I thought if I post it here it might lead to pointer about what is actually going on.:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xa0a734]

goroutine 3126 [running]:
github.com/42wim/matterbridge/bridge/discord/transmitter.(*Transmitter).HasWebhook(0x0, 0xc0051b5380, 0x12, 0xc005511300)
	/go/src/github.com/42wim/matterbridge/bridge/discord/transmitter/transmitter.go:99 +0x54
github.com/42wim/matterbridge/bridge/discord.(*Bdiscord).messageCreate(0xc0004408f0, 0xc0063c6000, 0xc0087aeb60)
	/go/src/github.com/42wim/matterbridge/bridge/discord/handlers.go:72 +0xb34
github.com/matterbridge/discordgo.messageCreateEventHandler.Handle(0xc0003e0f60, 0xc0063c6000, 0x1be37c0, 0xc0087aeb60)
	/go/src/github.com/42wim/matterbridge/vendor/github.com/matterbridge/discordgo/eventhandlers.go:497 +0x4b
created by github.com/matterbridge/discordgo.(*Session).handle
	/go/src/github.com/42wim/matterbridge/vendor/github.com/matterbridge/discordgo/event.go:171 +0x111
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Matterbridge version: 1.22.2

**Additional context**
My config is fine - doing this for quite some time and even if there are only two gateways in the config it still drops (some) messages

**Comment by 42wim** [comment]
@qaisjp something you would like to take a look at?:)

**Comment by geleeroyale** [comment]
Thank you for looking at my issue - I am testing with various configs so that should not pose a problem. 

Especially since it used to work and then suddenly did not anymore.

I strongly feel this is coming from Discord's side, so might not be related to matterbridge at all.

There is another thing - all my bridges servers are crypto communities. It became fashion there to have strange bot users that change their nicks whenever the price of an asset changes. This might be overloading the bridge. It would be awesome if it was possible to deactivate listening for Nick changes.

**Comment by 42wim** [comment]
Nick changes should not overload discord/the bridge, matterbridge. 
Discord is the one sending those updates, matterbridge shouldn't have any problem handling those, it's just changing some hashes.

I still need a config for the one that crashed, and it's something you can reproduce easily?

**Comment by 42wim** [comment]
Closed because no feedback

**Comment by Benau** [comment]
```
2022-05-22T09:57:02+08:00 error layer=debugger error loading binary "/usr/lib/libstdc++.so.6": could not parse .eh_frame section: pointer encoding not supported 0x9b at 0x118
> [unrecovered-panic] runtime.fatalpanic() /usr/lib/go/src/runtime/panic.go:1065 (hits goroutine(72):1 total:1) (PC: 0x44bd60)
Warning: debugging optimized function
	runtime.curg._panic.arg: interface {}(string) "runtime error: invalid memory address or nil pointer dereference"
  1060:	// fatalpanic implements an unrecoverable panic. It is like fatalthrow, except
  1061:	// that if msgs != nil, fatalpanic also prints panic messages and decrements
  1062:	// runningPanicDefers once main is blocked from exiting.
  1063:	//
  1064:	//go:nosplit
=>1065:	func fatalpanic(msgs *_panic) {
  1066:		pc := getcallerpc()
  1067:		sp := getcallersp()
  1068:		gp := getg()
  1069:		var docrash bool
  1070:		// Switch to the system stack to avoid any stack growth, which
(dlv) bt
 0  0x000000000044bd60 in runtime.fatalpanic
    at /usr/lib/go/src/runtime/panic.go:1065
 1  0x000000000044b5ba in runtime.gopanic
    at /usr/lib/go/src/runtime/panic.go:941
 2  0x0000000000449d25 in runtime.panicmem
    at /usr/lib/go/src/runtime/panic.go:220
 3  0x0000000000462525 in runtime.sigpanic
    at /usr/lib/go/src/runtime/signal_unix.go:818
 4  0x0000000000d082ae in github.com/42wim/matterbridge/bridge/discord/transmitter.(*Transmitter).HasWebhook
    at ./bridge/discord/transmitter/transmitter.go:99
 5  0x0000000000dae41d in github.com/42wim/matterbridge/bridge/discord.(*Bdiscord).messageCreate
    at ./bridge/discord/handlers.go:77
 6  0x0000000000dae268 in github.com/42wim/matterbridge/bridge/discord.(*Bdiscord).messageUpdate
    at ./bridge/discord/handlers.go:65
 7  0x0000000000db729f in github.com/42wim/matterbridge/bridge/discord.(*Bdiscord).messageUpdate-fm
    at <autogenerated>:1
 8  0x0000000000ca3073 in github.com/bwmarrin/discordgo.messageUpdateEventHandler.Handle
    at ./vendor/github.com/bwmarrin/discordgo/eventhandlers.go:854
 9  0x0000000000c9e4a2 in github.com/bwmarrin/discordgo.(*Session).handle.func1
    at ./vendor/github.com/bwmarrin/discordgo/event.go:171
10  0x000000000047f901 in runtime.goexit
    at /usr/lib/go/src/runtime/asm_amd64.s:1571
(dlv) up
> [unrecovered-panic] runtime.fatalpanic() /usr/lib/go/src/runtime/panic.go:1065 (hits goroutine(72):1 total:1) (PC: 0x44bd60)
Warning: debugging optimized function
Frame 1: /usr/lib/go/src/runtime/panic.go:941 (PC: 44b5ba)
   936:		// Because it is unsafe to call arbitrary user code after freezing
   937:		// the world, we call preprintpanics to invoke all necessary Error
   938:		// and String methods to prepare the panic strings before startpanic.
   939:		preprintpanics(gp._panic)
   940:	
=> 941:		fatalpanic(gp._panic) // should not return
   942:		*(*int)(nil) = 0      // not reached
   943:	}
   944:	
   945:	// getargp returns the location where the caller
   946:	// writes outgoing function call arguments.
(dlv) 
> [unrecovered-panic] runtime.fatalpanic() /usr/lib/go/src/runtime/panic.go:1065 (hits goroutine(72):1 total:1) (PC: 0x44bd60)
Warning: debugging optimized function
Frame 2: /usr/lib/go/src/runtime/panic.go:220 (PC: 449d25)
   215:	
   216:	var memoryError = error(errorString("invalid memory address or nil pointer dereference"))
   217:	
   218:	func panicmem() {
   219:		panicCheck2("invalid memory address or nil pointer dereference")
=> 220:		panic(memoryError)
   221:	}
   222:	
   223:	func panicmemAddr(addr uintptr) {
   224:		panicCheck2("invalid memory address or nil pointer dereference")
   225:		panic(errorAddressString{msg: "invalid memory address or nil pointer dereference", addr: addr})
(dlv) 
> [unrecovered-panic] runtime.fatalpanic() /usr/lib/go/src/runtime/panic.go:1065 (hits goroutine(72):1 total:1) (PC: 0x44bd60)
Warning: debugging optimized function
Frame 3: /usr/lib/go/src/runtime/signal_unix.go:818 (PC: 462525)
   813:			}
   814:			print("unexpected fault address ", hex(g.sigcode1), "\n")
   815:			throw("fault")
   816:		case _SIGSEGV:
   817:			if (g.sigcode0 == 0 || g.sigcode0 == _SEGV_MAPERR || g.sigcode0 == _SEGV_ACCERR) && g.sigcode1 < 0x1000 {
=> 818:				panicmem()
   819:			}
   820:			// Support runtime/debug.SetPanicOnFault.
   821:			if g.paniconfault {
   822:				panicmemAddr(g.sigcode1)
   823:			}
(dlv) 
> [unrecovered-panic] runtime.fatalpanic() /usr/lib/go/src/runtime/panic.go:1065 (hits goroutine(72):1 total:1) (PC: 0x44bd60)
Warning: debugging optimized function
Frame 4: ./bridge/discord/transmitter/transmitter.go:99 (PC: d082ae)
    94:		return nil
    95:	}
    96:	
    97:	// HasWebhook checks whether the transmitter is using a particular webhook.
    98:	func (t *Transmitter) HasWebhook(id string) bool {
=>  99:		t.mutex.RLock()
   100:		defer t.mutex.RUnlock()
   101:	
   102:		for _, wh := range t.channelWebhooks {
   103:			if wh.ID == id {
   104:				return true
(dlv) p t
*github.com/42wim/matterbridge/bridge/discord/transmitter.Transmitter nil
(dlv) p t.mutex
Command failed: t is nil
```
Sometimes I can reproduce it, does it help a little bit?
