### ISSUE TITLE
Getting Error While Scanning QR Code

### ISSUE THREAD

**Issue by rsoorajs** [42wim/matterbridge#1578]
New Whatsapp Beta added multi device Support.Usage of Whatsapp web even without need our mobile always online.But when we scanned the generated QR code on terminal using whatsapp beta,its shows below error.We need to join a feature called "Multi-device beta" to enable this support in whatsapp. When this feature is on,QR code failed to read,when feature is off qr code reads.but only we can stay online in Whatsapp web is using this feature in.so kindly fix this asap.

```
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/Rhymen/go-whatsapp.newInfoFromReq(0xc000176ba0, 0x38)
        /go/src/github.com/42wim/matterbridge/vendor/github.com/Rhymen/go-whatsapp/session.go:63 +0xc67
github.com/Rhymen/go-whatsapp.(*Conn).Login(0xc00010df00, 0xc000569560, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/42wim/matterbridge/vendor/github.com/Rhymen/go-whatsapp/session.go:268 +0xefb
github.com/42wim/matterbridge/bridge/whatsapp.(*Bwhatsapp).Login(0xc000176de0, 0x3, 0xc0000c7920)
        /go/src/github.com/42wim/matterbridge/bridge/whatsapp/whatsapp.go:138 +0x155
github.com/42wim/matterbridge/bridge/whatsapp.(*Bwhatsapp).Connect(0xc000176de0, 0x4, 0x201e0e1)
        /go/src/github.com/42wim/matterbridge/bridge/whatsapp/whatsapp.go:83 +0x70a
github.com/42wim/matterbridge/gateway.(*Router).Start(0xc00027a780, 0x22277b0, 0xc00003b290)
        /go/src/github.com/42wim/matterbridge/gateway/router.go:76 +0x493
main.main()
        /go/src/github.com/42wim/matterbridge/matterbridge.go:67 +0x509
```

**Comment by rsoorajs** [comment]
@42wim Can you please take a look in to this ?

**Comment by pazkero** [comment]
I believe #1702 may fix this.

**Comment by codinghedgehog-python** [comment]
By the way this is still an issue. Have tried the latest stable release as well as last 3 releases
and still throws the above error. How many people can't get a bot working between different apps ...

**Comment by pazkero** [comment]
I believe WhatsApp is dropping the legacy protocol. You will need to compile with whatsmeow, which works for me-- Jesusalva, TMW AdminSent from Yandex.Mail for mobile19:06, April 24, 2022, "codinghedgehog-python" ***@***.***>:
By the way this is still an issue. Have tried the latest stable release as well as last 3 releases
and still throws the above error. How many people can't get a bot working between different apps ...

**Comment by maka1000** [comment]
I still have this issue too, does anybody have a solution for this issue?

**Comment by pazkero** [comment]
You must compile with WhatsApp supporthttps://github.com/42wim/matterbridge#building-with-whatsapp-beta-multidevice-support-- Jesusalva, TMW AdminSent from Yandex.Mail for mobile07:13, July 9, 2022, maka1000 ***@***.***>:
I still have this issue too, does anybody have a solution for this issue?

**Comment by maka1000** [comment]
1. I checked my latest go version: "go version go1.18.3 linux/amd64"
2. I installed "If you're low on memory and don't need msteams:" with: go install -tags nomsteams,whatsappmulti github.com/42wim/matterbridge@master
3. I checked my go directory: Go is in Folder "/usr/local/go/bin/" but there is no "matterbridge binary" only "go" and "gofmt" is there.
Do you know how to solve this?

**Comment by pazkero** [comment]
I believe it'll be in $XDG_HOME/go/bin.So in my case, /home/jesusalva/go/binBeen a while, some details escape me right now.-- Jesusalva, TMW AdminSent from Yandex.Mail for mobile09:42, July 9, 2022, maka1000 ***@***.***>:

I checked my latest go version: "go version go1.18.3 linux/amd64"
I installed "If you're low on memory and don't need msteams:" with: go install -tags nomsteams,whatsappmulti ***@***.***
I checked my go directory: Go is in Folder "/usr/local/go/bin/" but there is no "matterbridge binary" only "go" and "gofmt" is there.
Do you know how to solve this?
