### ISSUE TITLE
Crash when configuration file contains a room that cannot be joined and a message is received

### ISSUE THREAD

**Issue by Mikaela** [42wim/matterbridge#1616]
**Describe the bug**

When the config file contains a room which cannot be joined, Matterbridge crashes whenever it receives a message and forwards it on another room.

**To Reproduce**

1. Configure matterbridge
2. Include rooms that cannot be joined
3. Say something in a room the bot is in
4. Observe the crash

**Expected behavior**

The bot keeps working in other rooms without a crash.

**Screenshots/debug logs**

> ```
> Oct 19 18:08:30 etro matterbridge[355229]: panic: runtime error: invalid memory address or nil pointer dereference                                                             
> Oct 19 18:08:30 etro matterbridge[355229]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x556f66]                                                              
> Oct 19 18:08:30 etro matterbridge[355229]: goroutine 2424 [running]:                                                                                                                                              
> Oct 19 18:08:30 etro matterbridge[355229]: github.com/sirupsen/logrus.(*Entry).Logln(0x0, 0x4, 0xc000565fa8, 0x2, 0x2)                                                         
> Oct 19 18:08:30 etro matterbridge[355229]:         /go/src/github.com/42wim/matterbridge/vendor/github.com/sirupsen/logrus/entry.go:382 +0x26                                  
> Oct 19 18:08:30 etro matterbridge[355229]: github.com/sirupsen/logrus.(*Entry).Infoln(...)                                                                                                                        
> Oct 19 18:08:30 etro matterbridge[355229]:         /go/src/github.com/42wim/matterbridge/vendor/github.com/sirupsen/logrus/entry.go:396                                        
> Oct 19 18:08:30 etro matterbridge[355229]: github.com/sirupsen/logrus.(*Entry).Println(...)                                                                                                                       
> Oct 19 18:08:30 etro matterbridge[355229]:         /go/src/github.com/42wim/matterbridge/vendor/github.com/sirupsen/logrus/entry.go:400                                                                           
> Oct 19 18:08:30 etro matterbridge[355229]: github.com/42wim/matterbridge/bridge/matrix.(*Bmatrix).handlematrix.func1(0xc0006165a0)
> Oct 19 18:08:30 etro matterbridge[355229]:         /go/src/github.com/42wim/matterbridge/bridge/matrix/matrix.go:305 +0xb9
> Oct 19 18:08:30 etro matterbridge[355229]: created by github.com/42wim/matterbridge/bridge/matrix.(*Bmatrix).handlematrix
> Oct 19 18:08:30 etro matterbridge[355229]:         /go/src/github.com/42wim/matterbridge/bridge/matrix/matrix.go:302 +0x345
> Oct 19 18:08:30 etro oragono[983]: 2021-10-19T15:08:30.188Z : info  : connect-ip : disconnecting session of T4 from ::1
> Oct 19 18:08:30 etro systemd[1]: matterbridge.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
> Oct 19 18:08:30 etro systemd[1]: matterbridge.service: Failed with result 'exit-code'.
> Oct 19 18:08:35 etro systemd[1]: matterbridge.service: Scheduled restart job, restart counter is at 3.
> Oct 19 18:08:35 etro systemd[1]: Stopped Matterbridge Daemon.
> Oct 19 18:08:35 etro systemd[1]: Started Matterbridge Daemon.
> ```

**Environment (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Matterbridge version: 1.23.0 55f41dda

**Additional context**

Example crashing block

```
    [[gateway.inout]]
    account="matrix.feneas"
    channel="!NHWhsRnOCtagrUcIFM:matrix.org"
```

**Comment by Mikaela** [comment]
Not fixed.

```
Nov 23 09:49:27 etro matterbridge[1673553]: time="2021-11-23T07:49:27Z" level=debug msg="== Receiving event: &gomatrix.Event{StateKey:(*string)(nil), Sender:"@mikaela.suomalainen:matrix.org", Type:"m.room.message", Timestamp:1637653767470, ID:"$o8xSb92w945tO8vf0i2onyeRs5PLawBbbYjr3Xp6nww", RoomID:"!ZvRwQrYiYaDAahKSst:matrix.org", Redacts:"", Unsigned:map[string]interface {}{"age":151}, Content:map[string]interface {}{"body":"/ping", "msgtype":"m.text"}, PrevContent:map[string]interface {}(nil)}" func=handleEvent file="bridge/matrix/matrix.go:354" prefix=matrix
Nov 23 09:49:27 etro matterbridge[1673553]: time="2021-11-23T07:49:27Z" level=info msg="Sync() returned  ProcessResponse panicked! userID=@mikaela.matterbridge:tedomum.net since=s68982522_267041475_615822_61297900_3825539_5662_2325438_25915354_26134 panic=runtime error: invalid memory address or nil pointer dereference
Nov 23 09:49:27 etro matterbridge[1673553]: goroutine 326 [running]:
Nov 23 09:49:27 etro matterbridge[1673553]: runtime/debug.Stack()
Nov 23 09:49:27 etro matterbridge[1673553]:         /usr/local/go/src/runtime/debug/stack.go:24 +0x65
Nov 23 09:49:27 etro matterbridge[1673553]: github.com/matrix-org/gomatrix.(*DefaultSyncer).ProcessResponse.func1()
Nov 23 09:49:27 etro matterbridge[1673553]:         /go/src/github.com/42wim/matterbridge/vendor/github.com/matrix-org/gomatrix/sync.go:52 +0x78
Nov 23 09:49:27 etro matterbridge[1673553]: panic({0x1d6a1e0, 0x3962df0})
Nov 23 09:49:27 etro matterbridge[1673553]:         /usr/local/go/src/runtime/panic.go:1038 +0x215
Nov 23 09:49:27 etro matterbridge[1673553]: github.com/42wim/matterbridge/bridge.(*Bridge).GetBool(0xc00052e480, {0x22096a2, 0xb})
Nov 23 09:49:27 etro matterbridge[1673553]:         /go/src/github.com/42wim/matterbridge/bridge/bridge.go:98 +0x5b
Nov 23 09:49:27 etro matterbridge[1673553]: github.com/42wim/matterbridge/bridge/matrix.(*Bmatrix).getDisplayName(0xc000548540, {0xc000c931a0, 0xc000c931c0})
Nov 23 09:49:27 etro matterbridge[1673553]:         /go/src/github.com/42wim/matterbridge/bridge/matrix/helpers.go:56 +0x58
Nov 23 09:49:27 etro matterbridge[1673553]: github.com/42wim/matterbridge/bridge/matrix.(*Bmatrix).handleEvent(0xc000548540, 0xc000598e80)
Nov 23 09:49:27 etro matterbridge[1673553]:         /go/src/github.com/42wim/matterbridge/bridge/matrix/matrix.go:366 +0x1a5
Nov 23 09:49:27 etro matterbridge[1673553]: github.com/matrix-org/gomatrix.(*DefaultSyncer).notifyListeners(0xc0005d0f00, 0xc000598e80)
Nov 23 09:49:27 etro matterbridge[1673553]:         /go/src/github.com/42wim/matterbridge/vendor/github.com/matrix-org/gomatrix/sync.go:156 +0x72
Nov 23 09:49:27 etro matterbridge[1673553]: github.com/matrix-org/gomatrix.(*DefaultSyncer).ProcessResponse(0xc0005d0f00, 0xc00091d560, {0xc001148320, 0x47})
Nov 23 09:49:27 etro matterbridge[1673553]:         /go/src/github.com/42wim/matterbridge/vendor/github.com/matrix-org/gomatrix/sync.go:65 +0x9dc
Nov 23 09:49:27 etro matterbridge[1673553]: github.com/matrix-org/gomatrix.(*Client).Sync(0xc000598280)
Nov 23 09:49:27 etro matterbridge[1673553]:         /go/src/github.com/42wim/matterbridge/vendor/github.com/matrix-org/gomatrix/client.go:153 +0x219
Nov 23 09:49:27 etro matterbridge[1673553]: github.com/42wim/matterbridge/bridge/matrix.(*Bmatrix).handlematrix.func1()
Nov 23 09:49:27 etro matterbridge[1673553]:         /go/src/github.com/42wim/matterbridge/bridge/matrix/matrix.go:307 +0x35
Nov 23 09:49:27 etro matterbridge[1673553]: created by github.com/42wim/matterbridge/bridge/matrix.(*Bmatrix).handlematrix
Nov 23 09:49:27 etro matterbridge[1673553]:         /go/src/github.com/42wim/matterbridge/bridge/matrix/matrix.go:302 +0x46f
Nov 23 09:49:27 etro matterbridge[1673553]: " func=func1 file="bridge/matrix/matrix.go:308" prefix=matrix
Nov 23 09:49:44 etro matterbridge[1673553]: time="2021-11-23T07:49:44Z" level=debug msg=PING func=func1 file="bridge/xmpp/xmpp.go:265" prefix=xmpp
```

version: 1.23.1 9afd33cd
