### ISSUE TITLE
Messages don't get relayed from WhatsApp multi if they contain a link with preview

### ISSUE THREAD

**Issue by reckel-jm** [42wim/matterbridge#1840]
**Describe the bug**
A message from WhatsApp Multi does not get relayed if it contains a link with preview enabled. If the preview is not sent, the message will be forwarded without a problem.

**To Reproduce**
Send a WhatsApp message with link and preview.

**Expected behavior**
The message should be relayed as normal.

**Environment (please complete the following information):**
 - OS: Linux
 - Matterbridge version: v1.25.1
 - e6183091a811decb45b651494a55b003e5cd9430

**Log Messages:**

```
[0195]  INFO whatsapp:     Receiving message &proto.Message{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(0xc000807870)}, sizeCache:0, unknownFields:[]uint8(nil), Conversation:(*string)(nil), SenderKeyDistributionMessage:(*proto.SenderKeyDistributionMessage)(nil), ImageMessage:(*proto.ImageMessage)(nil), ContactMessage:(*proto.ContactMessage)(nil), LocationMessage:(*proto.LocationMessage)(nil), ExtendedTextMessage:(*proto.ExtendedTextMessage)(0xc000a92f00), DocumentMessage:(*proto.DocumentMessage)(nil), AudioMessage:(*proto.AudioMessage)(nil), VideoMessage:(*proto.VideoMessage)(nil), Call:(*proto.Call)(nil), Chat:(*proto.Chat)(nil), ProtocolMessage:(*proto.ProtocolMessage)(nil), ContactsArrayMessage:(*proto.ContactsArrayMessage)(nil), HighlyStructuredMessage:(*proto.HighlyStructuredMessage)(nil), FastRatchetKeySenderKeyDistributionMessage:(*proto.SenderKeyDistributionMessage)(nil), SendPaymentMessage:(*proto.SendPaymentMessage)(nil), LiveLocationMessage:(*proto.LiveLocationMessage)(nil), RequestPaymentMessage:(*proto.RequestPaymentMessage)(nil), DeclinePaymentRequestMessage:(*proto.DeclinePaymentRequestMessage)(nil), CancelPaymentRequestMessage:(*proto.CancelPaymentRequestMessage)(nil), TemplateMessage:(*proto.TemplateMessage)(nil), StickerMessage:(*proto.StickerMessage)(nil), GroupInviteMessage:(*proto.GroupInviteMessage)(nil), TemplateButtonReplyMessage:(*proto.TemplateButtonReplyMessage)(nil), ProductMessage:(*proto.ProductMessage)(nil), DeviceSentMessage:(*proto.DeviceSentMessage)(nil), MessageContextInfo:(*proto.MessageContextInfo)(nil), ListMessage:(*proto.ListMessage)(nil), ViewOnceMessage:(*proto.FutureProofMessage)(nil), OrderMessage:(*proto.OrderMessage)(nil), ListResponseMessage:(*proto.ListResponseMessage)(nil), EphemeralMessage:(*proto.FutureProofMessage)(nil), InvoiceMessage:(*proto.InvoiceMessage)(nil), ButtonsMessage:(*proto.ButtonsMessage)(nil), ButtonsResponseMessage:(*proto.ButtonsResponseMessage)(nil), PaymentInviteMessage:(*proto.PaymentInviteMessage)(nil), InteractiveMessage:(*proto.InteractiveMessage)(nil), ReactionMessage:(*proto.ReactionMessage)(nil), StickerSyncRmrMessage:(*proto.StickerSyncRMRMessage)(nil), InteractiveResponseMessage:(*proto.InteractiveResponseMessage)(nil), PollCreationMessage:(*proto.PollCreationMessage)(nil), PollUpdateMessage:(*proto.PollUpdateMessage)(nil)}
10:07:35.130 [Client ERROR] Event handler panicked while handling a *events.Message: runtime error: invalid memory address or nil pointer dereference
goroutine 24 [running]:
runtime/debug.Stack()
        /usr/lib/go-1.17/src/runtime/debug/stack.go:24 +0x65
go.mau.fi/whatsmeow.(*Client).dispatchEvent.func1()
        /home/wuki/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220504135614-f1f2a9d231fb/client.go:531 +0x7d
panic({0x1736ae0, 0x29abc00})
        /usr/lib/go-1.17/src/runtime/panic.go:1038 +0x215
github.com/42wim/matterbridge/bridge/whatsappmulti.(*Bwhatsapp).handleTextMessage(_, {{{{0xc00067d4a0, 0x12}, 0x0, 0x0, {0x19e903e, 0x4}, 0x0}, {{0xc000dddb00, 0xc}, ...}, ...}, ...}, ...)
        /home/wuki/go/pkg/mod/github.com/42wim/matterbridge@v1.25.1/bridge/whatsappmulti/handlers.go:77 +0x2b7
github.com/42wim/matterbridge/bridge/whatsappmulti.(*Bwhatsapp).handleMessage(0xc00087d600, 0xc000a93040)
        /home/wuki/go/pkg/mod/github.com/42wim/matterbridge@v1.25.1/bridge/whatsappmulti/handlers.go:37 +0x165
github.com/42wim/matterbridge/bridge/whatsappmulti.(*Bwhatsapp).eventHandler(...)
        /home/wuki/go/pkg/mod/github.com/42wim/matterbridge@v1.25.1/bridge/whatsappmulti/handlers.go:22
go.mau.fi/whatsmeow.(*Client).dispatchEvent(0x193a7e0, {0x1603be0, 0xc000a93040})
        /home/wuki/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220504135614-f1f2a9d231fb/client.go:535 +0x118
go.mau.fi/whatsmeow.(*Client).handleDecryptedMessage(0xc0004f0000, 0xc000e12b40, 0xc000afc300)
        /home/wuki/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220504135614-f1f2a9d231fb/message.go:402 +0x4e5
go.mau.fi/whatsmeow.(*Client).decryptMessages(0xc0004f0000, 0xc000e12b40, 0xc000e280c0)
        /home/wuki/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220504135614-f1f2a9d231fb/message.go:167 +0x8da
go.mau.fi/whatsmeow.(*Client).handleEncryptedMessage(0xc0004f0000, 0x0)
        /home/wuki/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220504135614-f1f2a9d231fb/message.go:46 +0x19f
go.mau.fi/whatsmeow.(*Client).handlerQueueLoop(0xc0004f0000, {0x1cb1038, 0xc00087d240})
        /home/wuki/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220504135614-f1f2a9d231fb/client.go:487 +0x6b
created by go.mau.fi/whatsmeow.(*Client).Connect
        /home/wuki/go/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220504135614-f1f2a9d231fb/client.go:252 +0x44f
```

**Comment by DorFriesch** [comment]
I do have the same issue. Is there any fix or workaround already?
