### ISSUE TITLE
Crashes when adding a discord bridge?

### ISSUE THREAD

**Issue by RhinosF1** [42wim/matterbridge#1988]
**Describe the bug**
```
Feb 26 10:42:37 bots3001.fossbots.org matterbridge[1274898]: time="2023-02-26T10:42:37Z" level=info msg="Starting bridge: discord.miraheze " prefix=router
Feb 26 10:42:37 bots3001.fossbots.org matterbridge[1274898]: time="2023-02-26T10:42:37Z" level=info msg=Connecting prefix=discord
Feb 26 10:42:37 bots3001.fossbots.org matterbridge[1274898]: time="2023-02-26T10:42:37Z" level=info msg="Connection succeeded" prefix=discord
Feb 26 10:42:37 bots3001.fossbots.org matterbridge[1274898]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 26 10:42:37 bots3001.fossbots.org matterbridge[1274898]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x54b3bc]
Feb 26 10:42:37 bots3001.fossbots.org matterbridge[1274898]: goroutine 1509 [running]:
Feb 26 10:42:37 bots3001.fossbots.org matterbridge[1274898]: github.com/42wim/matterbridge/bridge/discord/transmitter.(*Transmitter).HasWebhook(0x1cdf2d8?, {0x4000bc1680?, 0x0?})
Feb 26 10:42:37 bots3001.fossbots.org matterbridge[1274898]:         /go/src/github.com/42wim/matterbridge/bridge/discord/transmitter/transmitter.go:99 +0x2c
Feb 26 10:42:37 bots3001.fossbots.org matterbridge[1274898]: github.com/42wim/matterbridge/bridge/discord.(*Bdiscord).messageCreate(0x40001d2600, 0x1?, 0x40009ae7a0)
Feb 26 10:42:37 bots3001.fossbots.org matterbridge[1274898]:         /go/src/github.com/42wim/matterbridge/bridge/discord/handlers.go:77 +0x8c
Feb 26 10:42:37 bots3001.fossbots.org matterbridge[1274898]: github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0x4000afcba0?, 0x0?, {0x1756ba0?, 0x40009ae7a0?})
Feb 26 10:42:37 bots3001.fossbots.org matterbridge[1274898]:         /go/src/github.com/42wim/matterbridge/vendor/github.com/bwmarrin/discordgo/eventhandlers.go:734 +0x48
Feb 26 10:42:37 bots3001.fossbots.org matterbridge[1274898]: created by github.com/bwmarrin/discordgo.(*Session).handle
Feb 26 10:42:37 bots3001.fossbots.org matterbridge[1274898]:         /go/src/github.com/42wim/matterbridge/vendor/github.com/bwmarrin/discordgo/event.go:171 +0x160
Feb 26 10:42:37 bots3001.fossbots.org systemd[1]: matterbridge.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 26 10:42:37 bots3001.fossbots.org systemd[1]: matterbridge.service: Failed with result 'exit-code'.
```

**To Reproduce**
Unknown - config was https://github.com/FOSSBots/puppet/blob/4fdf30c3d53e371e5f214b85c2cb9335432ff5c0/modules/profile/templates/matterbridge.toml
**Expected behavior**
No crashes

**Screenshots/debug logs**
Use logs from running `matterbridge -debug` if possible.
see above

**Environment (please complete the following information):**
 - OS: [e.g. linux]
 - Matterbridge version: output of  `matterbridge -version`
 - If self compiled: output of `git rev-parse HEAD`
1.25.1

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))
config: https://github.com/FOSSBots/puppet/blob/4fdf30c3d53e371e5f214b85c2cb9335432ff5c0/modules/profile/templates/matterbridge.toml

**Comment by 42wim** [comment]
This should be fixed now in master
