### ISSUE TITLE
Crash while connecting and SASL authentication ?

### ISSUE THREAD

**Issue by NikkyAI** [42wim/matterbridge#214]
Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
version: 0.16.0-dev

### Please describe the actual behavior. 
matterridge crashed over night

last lines of the debug output..
```
DEBU[2017-07-07T12:43:04+02:00] ":ipo.esper.net PONG ipo.esper.net :1499424184046019941"  module=irc
DEBU[2017-07-07T12:44:04+02:00] ":ipo.esper.net PONG ipo.esper.net :1499424244045992431"  module=irc
DEBU[2017-07-07T12:45:04+02:00] ":ipo.esper.net PONG ipo.esper.net :1499424304045974107"  module=irc
DEBU[2017-07-07T12:46:04+02:00] ":ipo.esper.net PONG ipo.esper.net :1499424364045992956"  module=irc
DEBU[2017-07-07T12:47:04+02:00] ":ipo.esper.net PONG ipo.esper.net :1499424424045996567"  module=irc
DEBU[2017-07-07T12:48:05+02:00] ":ipo.esper.net PONG ipo.esper.net :1499424484046575261"  module=irc
2017/07/07 12:50:05 Error, disconnected: read tcp [2a03:4000:6:e105::1]:45590->[2001:1ad8:8:5555::]:6697: i/o timeout
2017/07/07 12:50:05 Connected to irc.esper.net:6697 ([2600:3c03::f03c:91ff:feb0:ece]:6697)
DEBU[2017-07-07T12:50:06+02:00] ":stormlight.esper.net NOTICE * :*** Looking up your hostname..."  module=irc
DEBU[2017-07-07T12:50:06+02:00] ":stormlight.esper.net NOTICE * :*** Checking Ident"  module=irc
DEBU[2017-07-07T12:50:06+02:00] ":stormlight.esper.net NOTICE * :*** Found your hostname"  module=irc
DEBU[2017-07-07T12:50:06+02:00] ":stormlight.esper.net NOTICE * :*** No Ident response"  module=irc
DEBU[2017-07-07T12:50:06+02:00] ":stormlight.esper.net CAP * LS :account-notify away-notify cap-notify chghost extend
ed-join multi-prefix sasl tls userhost-in-names"  module=irc
DEBU[2017-07-07T12:50:06+02:00] ":stormlight.esper.net CAP * ACK :sasl"       module=irc
DEBU[2017-07-07T12:50:07+02:00] "AUTHENTICATE +"                              module=irc
2017/07/07 12:50:20 Error while reconnecting: SASL setup timed out. This shouldn't happen.
2017/07/07 12:51:20 Error, disconnected: SASL setup timed out. This shouldn't happen.
2017/07/07 12:51:42 Error while reconnecting: EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6203c2]

goroutine 19793 [running]:
crypto/tls.(*Conn).SetWriteDeadline(0x0, 0xed0f15f11, 0x38b55ca1, 0x1042cc0, 0x1, 0x0)
        /usr/lib/go/src/crypto/tls/conn.go:136 +0x22
github.com/42wim/matterbridge/vendor/github.com/thoj/go-ircevent.(*Connection).writeLoop(0xc4201c4580)
        /home/nikky/go/src/github.com/42wim/matterbridge/vendor/github.com/thoj/go-ircevent/irc.go:143 +0x23e
created by github.com/42wim/matterbridge/vendor/github.com/thoj/go-ircevent.(*Connection).Connect
        /home/nikky/go/src/github.com/42wim/matterbridge/vendor/github.com/thoj/go-ircevent/irc.go:427 +0x6eb
```

**Comment by 42wim** [comment]
It's a problem with the underlying irc library.
I've gotten that issue too, but it happens very rarely.
For now you better set matterbridge under a supervisor, like systemd, so that it automatically gets restarted after a crash.

Maybe you can also report it at https://github.com/thoj/go-ircevent/issues

If you have steps to reproduce it easily then I could take a look and try to fix it myself.

**Comment by NikkyAI** [comment]
is there ready to use systemd service files ?

**Comment by 42wim** [comment]
See https://github.com/42wim/matterbridge/issues/116#issuecomment-299642840 for an example

**Comment by 42wim** [comment]
@NikkyAI Are you still having those crashes ? 28 July I've updated the irc library with some SASL changes.
If you still got those, please reopen.
