### ISSUE TITLE
is whatsapp no longer working?

### ISSUE THREAD

**Issue by Googlegithb** [42wim/matterbridge#2150]
01:35:39.122 [Client ERROR] Client outdated (405) connect failure (client version: 2.2332.15)
[0002]  INFO whatsapp:     QR channel result: err-client-outdated
[0004]  INFO whatsapp:     WhatsApp connection successful
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12f41e2]

goroutine 1 [running]:
github.com/42wim/matterbridge/bridge/whatsappmulti.(*Bwhatsapp).Connect(0xc00029e600)
        /root/go/pkg/mod/github.com/42wim/matterbridge@v1.26.1-0.20230805184319-56e7bd01ca09/bridge/whatsappmulti/whatsapp.go:125 +0x602
github.com/42wim/matterbridge/gateway.(*Router).Start(0xc00017d0e0)
        /root/go/pkg/mod/github.com/42wim/matterbridge@v1.26.1-0.20230805184319-56e7bd01ca09/gateway/router.go:76 +0x345
main.main()
        /root/go/pkg/mod/github.com/42wim/matterbridge@v1.26.1-0.20230805184319-56e7bd01ca09/matterbridge.go:65 +0x39e

**Comment by Schattenkanzler** [comment]
-> #2146

**Comment by kaizenGG** [comment]
who can fix me for me? i can pay 10$

tg: darthvadertips

thanks

**Comment by rodrigozietlow** [comment]
You can try #2148, just follow instructions on #2146 for local compilation
