### ISSUE TITLE
panic: reflect: call of reflect.Value.Interface on zero Value

### ISSUE THREAD

**Issue by dsslimshaddy** [42wim/matterbridge#319]
```
INFO[2017-12-15T04:18:11-06:00] Running version 1.5.1 bb38a61                
panic: reflect: call of reflect.Value.Interface on zero Value

goroutine 1 [running]:
reflect.valueInterface(0x0, 0x0, 0x0, 0xc420273001, 0xc0f2a0, 0xc420273060)
	/usr/local/go/src/reflect/value.go:936 +0x1bf
reflect.Value.Interface(0x0, 0x0, 0x0, 0xc0f2a0, 0xc420273060)
	/usr/local/go/src/reflect/value.go:931 +0x44
github.com/42wim/matterbridge/bridge/config.OverrideCfgFromEnv(0xc420394000, 0xc420017480, 0x7, 0xc420017488, 0x8)
	/go/src/github.com/42wim/matterbridge/bridge/config/config.go:189 +0x311
github.com/42wim/matterbridge/bridge.New(0xc420394000, 0xc4201ebb88, 0xc42007a1e0, 0x0)
	/go/src/github.com/42wim/matterbridge/bridge/bridge.go:50 +0x23e
github.com/42wim/matterbridge/gateway.(*Gateway).AddBridge(0xc42038f4f0, 0xc4201ebb88, 0x2, 0x2)
	/go/src/github.com/42wim/matterbridge/gateway/gateway.go:48 +0x111
github.com/42wim/matterbridge/gateway.(*Gateway).AddConfig(0xc42038f4f0, 0xc42025e8a0, 0xc42039c690, 0x0)
	/go/src/github.com/42wim/matterbridge/gateway/gateway.go:60 +0x258
github.com/42wim/matterbridge/gateway.New(0xc42001b3f0, 0x8, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4202701b0, ...)
	/go/src/github.com/42wim/matterbridge/gateway/gateway.go:41 +0x289
github.com/42wim/matterbridge/gateway.NewRouter(0xc420394000, 0x11, 0xc420394000, 0x4)
	/go/src/github.com/42wim/matterbridge/gateway/router.go:37 +0x2c3
main.main()
	/go/src/github.com/42wim/matterbridge/matterbridge.go:46 +0x3f5

```

```
[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="discord.mydicord"
channel="general"

[[gateway.inout]]
account="slack.myslack"
channel="general"

```

**Comment by dsslimshaddy** [comment]
`account="discord.mydicord"` silly me
