### ISSUE TITLE
panic matrix

### ISSUE THREAD

**Issue by dajohi** [42wim/matterbridge#333]
version: 1.7.0-dev 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x810e8a]

goroutine 38 [running]:
github.com/42wim/matterbridge/bridge/matrix.(*Bmatrix).Send(0xc420231ec0, 0xc42030c600, 0xb4, 0xc4200697a0, 0x12, 0xc42054ff60, 0x18, 0xc42054c5a0, 0xa, 0x0, ...)
        /home/dhill/.go/src/github.com/42wim/matterbridge/bridge/matrix/matrix.go:135 +0xc5a
github.com/42wim/matterbridge/gateway.(*Gateway).handleMessage(0xc420391860, 0xc42030c600, 0xb4, 0xc4200697a0, 0x12, 0xc42054ff60, 0x18, 0xc42054c5a0, 0xa, 0x0, ...)
        /home/dhill/.go/src/github.com/42wim/matterbridge/gateway/gateway.go:202 +0x34f
github.com/42wim/matterbridge/gateway.(*Router).handleReceive(0xc42039ef80)
        /home/dhill/.go/src/github.com/42wim/matterbridge/gateway/router.go:104 +0x2cc
created by github.com/42wim/matterbridge/gateway.(*Router).Start
        /home/dhill/.go/src/github.com/42wim/matterbridge/gateway/router.go:60 +0x555
```

**Comment by 42wim** [comment]
Should be fixed in master now
