### ISSUE TITLE
panic - irc related

### ISSUE THREAD

**Issue by dajohi** [42wim/matterbridge#385]
version: 1.8.1-dev 

```
.....
[2018-03-05T14:55:00Z] ERROR irc:          error: timed out during ping to server                                        
[2018-03-05T14:55:00Z]  INFO irc:          reconnecting in 30 seconds...                                                 
panic: runtime error: invalid memory address or nil pointer dereference                                                  
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7dd34f]                                                   

goroutine 112 [running]:      
github.com/42wim/matterbridge/vendor/github.com/lrstanley/girc.(*ircConn).rate(0x0, 0x48, 0x0)                           
        /home/dhill/.go/src/github.com/42wim/matterbridge/vendor/github.com/lrstanley/girc/conn.go:405 +0x2f             
github.com/42wim/matterbridge/vendor/github.com/lrstanley/girc.(*Client).Send(0xc420774580, 0xc4203894a0)                
        /home/dhill/.go/src/github.com/42wim/matterbridge/vendor/github.com/lrstanley/girc/conn.go:383 +0x18c            
github.com/42wim/matterbridge/vendor/github.com/lrstanley/girc.(*Commands).Message(0xc42047a230, 0xc4203b66b0, 0x7, 0xc4200f6400, 0x37)
        /home/dhill/.go/src/github.com/42wim/matterbridge/vendor/github.com/lrstanley/girc/commands.go:108 +0xf7         
github.com/42wim/matterbridge/bridge/irc.(*Birc).doSend(0xc4203d2440)                                                    
        /home/dhill/.go/src/github.com/42wim/matterbridge/bridge/irc/irc.go:233 +0x1d0                                   
created by github.com/42wim/matterbridge/bridge/irc.(*Birc).Connect                                                      
        /home/dhill/.go/src/github.com/42wim/matterbridge/bridge/irc/irc.go:140 +0x76a  
```

**Comment by 42wim** [comment]
Hm strange, must be a race condition somewhere, I can't reproduce this crash.  
What commit are you on ?

**Comment by 42wim** [comment]
Found the issue, thanks for reporting!
