### ISSUE TITLE
panic - telegram related

### ISSUE THREAD

**Issue by dajohi** [42wim/matterbridge#386]
version: 1.8.1-dev 

crashed on startup.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0xb60876]

goroutine 39 [running]:
github.com/42wim/matterbridge/bridge/telegram.(*Btelegram).handleRecv(0xc4203ee300, 0xc420050240)
        /home/dhill/.go/src/github.com/42wim/matterbridge/bridge/telegram/telegram.go:174 +0xaf6
created by github.com/42wim/matterbridge/bridge/telegram.(*Btelegram).Connect
        /home/dhill/.go/src/github.com/42wim/matterbridge/bridge/telegram/telegram.go:41 +0x339
```

**Comment by 42wim** [comment]
Thanks for reporting, just fixed in master
