### ISSUE TITLE
SASL+TLS leads to connection failure

### ISSUE THREAD

**Issue by ishitatsuyuki** [42wim/matterbridge#39]
As the title says, the connection fails and the bridge crashes with NPE.

TLS+NickServ is okay, SASL without TLS also works. Since it's TLS, no packet inspection can be easily done on my side.
Although this may be an upstream issue, since you are the writer of the SASL part I'm writing here.

**Comment by 42wim** [comment]
Could you paste the crash ? I'm using TLS+SASL myself without any issues (on freenode)

**Comment by ishitatsuyuki** [comment]
```
INFO[2016-10-01T13:01:39+09:00] Connecting irc.freenode.net:6667              module=irc
INFO[2016-10-01T13:01:39+09:00] irc.freenode: joining #channel               
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x57a4fd]

goroutine 6 [running]:
panic(0x8db4a0, 0xc420014090)
        /usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/42wim/matterbridge/vendor/github.com/thoj/go-ircevent.(*Connection).Join(0x0, 0xc420151640, 0x8)
        /tmp/tmp.1oFiqQFJL5/src/github.com/42wim/matterbridge/vendor/github.com/thoj/go-ircevent/irc.go:221 +0xdd
github.com/42wim/matterbridge/bridge/irc.(*Birc).JoinChannel(0xc420017540, 0xc420151640, 0x8, 0x2, 0x2)
        /tmp/tmp.1oFiqQFJL5/src/github.com/42wim/matterbridge/bridge/irc/irc.go:78 +0x42
github.com/42wim/matterbridge/gateway.New(0xc420017310, 0xc4200174f0, 0x0, 0x0)
        /tmp/tmp.1oFiqQFJL5/src/github.com/42wim/matterbridge/gateway/gateway.go:45 +0xa81
main.main.func1(0xc420017310, 0xc420150d60, 0x7, 0x1, 0xc42006ec60, 0x3, 0x3, 0xc42006ecc0, 0x3, 0x3)
        /tmp/tmp.1oFiqQFJL5/src/github.com/42wim/matterbridge/matterbridge.go:39 +0x82
created by main.main
        /tmp/tmp.1oFiqQFJL5/src/github.com/42wim/matterbridge/matterbridge.go:43 +0x40d
```

**Comment by 42wim** [comment]
I've added verbose debugging of the IRC bridge connection when you enable debug. You can now debug SASL and compare it with and without TLS. It should be exactly the same though.

The gateway now also when a bridge fails to startup. So no NPE anymore.

**Comment by ishitatsuyuki** [comment]
hmm, the NPE disappeared, but no debug log is shown. I have no idea it's broken.

**Comment by 42wim** [comment]
You did run matterbridge with -debug?

**Comment by ishitatsuyuki** [comment]
Sure.

**Comment by 42wim** [comment]
Could you paste your config?

**Comment by ishitatsuyuki** [comment]
Wow, figured out now. It was the IRC port settings. No debug output there, though.
