### ISSUE TITLE
Crash... not sure why

### ISSUE THREAD

**Issue by robguthrie** [42wim/matterbridge#41]
I'm not sure if this is helpful, but matterbridge is crashing for me. Here is the stacktrace:

```
matterbridge_1 | panic: runtime error: invalid memory address or nil pointer dereference
matterbridge_1 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f5341d35d6b]
matterbridge_1 | 
matterbridge_1 | goroutine 6 [running]:
matterbridge_1 | panic(0x7f534239d1a0, 0xc42000c050)
matterbridge_1 | 	/usr/lib/go/src/runtime/panic.go:500 +0x1a5
matterbridge_1 | github.com/42wim/matterbridge/bridge/slack.(*Bslack).SendType(0xc4201015e0, 0xc4203bb3d8, 0x8, 0xc4203c6570, 0x28, 0xc4203f4610, 0xb, 0x0, 0x0, 0x0, ...)
matterbridge_1 | 	/go/src/github.com/42wim/matterbridge/bridge/slack/slack.go:118 +0x29b
matterbridge_1 | github.com/42wim/matterbridge/bridge/slack.(*Bslack).Send(0xc4201015e0, 0xc420403620, 0x1f, 0xc4203f4610, 0xb, 0xc4203bb3d8, 0x8, 0xc4201281ab, 0x8, 0xc4203dea20, ...)
matterbridge_1 | 	/go/src/github.com/42wim/matterbridge/bridge/slack/slack.go:96 +0x1ca
matterbridge_1 | github.com/42wim/matterbridge/gateway/samechannel.(*SameChannelGateway).handleMessage(0xc420041e98, 0xc420403620, 0x1f, 0xc4203f4610, 0xb, 0xc4203bb3d8, 0x8, 0xc4201281ab, 0x8, 0xc4203dea20, ...)
matterbridge_1 | 	/go/src/github.com/42wim/matterbridge/gateway/samechannel/samechannel.go:63 +0x24e
matterbridge_1 | github.com/42wim/matterbridge/gateway/samechannel.(*SameChannelGateway).handleReceive(0xc420041e98, 0xc420050c60)
matterbridge_1 | 	/go/src/github.com/42wim/matterbridge/gateway/samechannel/samechannel.go:50 +0x116
matterbridge_1 | github.com/42wim/matterbridge/gateway/samechannel.New(0xc420050a80, 0xc420011400, 0x0, 0x0)
matterbridge_1 | 	/go/src/github.com/42wim/matterbridge/gateway/samechannel/samechannel.go:41 +0x5bb
matterbridge_1 | main.main.func1(0xc420050a80, 0xc420128020, 0xf, 0x1, 0xc420101340, 0x7, 0x7, 0xc420128ec0, 0x2, 0x2)
matterbridge_1 | 	/go/src/github.com/42wim/matterbridge/matterbridge.go:40 +0x84
matterbridge_1 | created by main.main
matterbridge_1 | 	/go/src/github.com/42wim/matterbridge/matterbridge.go:44 +0x5c5
```

**Comment by taoeffect** [comment]
I had that too, it turned out to be because I prefixed slack channels with a `#`. Just remove it if you have that and it should fix it.

**Comment by 42wim** [comment]
@robguthrie I've hanlded the error correctly now in master, you should get an error message now. @taoeffect is probably right though :)

**Comment by 42wim** [comment]
Going to close this for now.
