### ISSUE TITLE
Cannot compile on low memory system

### ISSUE THREAD

**Issue by bparker06** [42wim/matterbridge#497]
**Describe the bug**
When compiling on an Amazon EC2 instance with `go get` on a system with 542MB RAM, it fails with an "out of memory" error.

**To Reproduce**
```
$ free
              total        used        free      shared  buff/cache   available
Mem:         542832      234812      209548         336       98472      294404
Swap:             0           0           0

$ go get github.com/42wim/matterbridge
# github.com/42wim/matterbridge/vendor/github.com/peterhellberg/emojilib
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xcabe37, 0x16)
        /usr/lib/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc00c000000, 0x4000000, 0x1377398)
        /usr/lib/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x13546e0, 0x4000000, 0x13548c8, 0x7f1eefe9a900)
        /usr/lib/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x13546e0, 0x24, 0x0)
        /usr/lib/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x13546e0, 0x24, 0x13773a8, 0x9000)
        /usr/lib/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x13546e0, 0x24, 0x100, 0x7f1eefc40fff)
        /usr/lib/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
        /usr/lib/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x13546e0, 0x24, 0x7f1eef010100, 0x4)
        /usr/lib/go/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x46368, 0x7ffe95df0001, 0x45431a)
        /usr/lib/go/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
        /usr/lib/go/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x455a89)
        /usr/lib/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/lib/go/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/lib/go/src/runtime/asm_amd64.s:311 fp=0xc004339910 sp=0xc004339908 pc=0x455b80
runtime.mallocgc(0x46368, 0xc8c900, 0xc000023701, 0xc0000242a0)
        /usr/lib/go/src/runtime/malloc.go:913 +0x896 fp=0xc0043399b0 sp=0xc004339910 pc=0x40bb16
runtime.makeslice(0xc8c900, 0x8c6d, 0x8c6d, 0x4, 0xc0034bfcb8, 0x1)
        /usr/lib/go/src/runtime/slice.go:70 +0x77 fp=0xc0043399e0 sp=0xc0043399b0 pc=0x43f2c7
cmd/compile/internal/ssa.fuseBlockPlain(0xc0034bf8c0, 0x47bd00)
        /usr/lib/go/src/cmd/compile/internal/ssa/fuse.go:165 +0x588 fp=0xc004339a88 sp=0xc0043399e0 pc=0x5fe828
cmd/compile/internal/ssa.fuse(0xc0002f2840)
        /usr/lib/go/src/cmd/compile/internal/ssa/fuse.go:19 +0x5f fp=0xc004339ac0 sp=0xc004339a88 pc=0x5fde0f
cmd/compile/internal/ssa.Compile(0xc0002f2840)
        /usr/lib/go/src/cmd/compile/internal/ssa/compile.go:70 +0x30e fp=0xc00433d4b0 sp=0xc004339ac0 pc=0x5dc01e
cmd/compile/internal/gc.buildssa(0xc0002f3a20, 0x0, 0x0)
        /usr/lib/go/src/cmd/compile/internal/gc/ssa.go:211 +0xab0 fp=0xc00433d5c8 sp=0xc00433d4b0 pc=0xb33310
cmd/compile/internal/gc.compileSSA(0xc0002f3a20, 0x0)
        /usr/lib/go/src/cmd/compile/internal/gc/pgen.go:259 +0x39 fp=0xc00433d630 sp=0xc00433d5c8 pc=0xb003f9
cmd/compile/internal/gc.compile(0xc0002f3a20)
        /usr/lib/go/src/cmd/compile/internal/gc/pgen.go:238 +0x1a0 fp=0xc00433d680 sp=0xc00433d630 pc=0xb00370
cmd/compile/internal/gc.funccompile(0xc0002f3a20)
        /usr/lib/go/src/cmd/compile/internal/gc/pgen.go:209 +0xbd fp=0xc00433d6d8 sp=0xc00433d680 pc=0xb000dd
cmd/compile/internal/gc.fninit(0xc00007a0a0, 0xd, 0x14)
        /usr/lib/go/src/cmd/compile/internal/gc/init.go:212 +0xaab fp=0xc00433d890 sp=0xc00433d6d8 pc=0xacb1bb
cmd/compile/internal/gc.Main(0xcc0f50)
        /usr/lib/go/src/cmd/compile/internal/gc/main.go:644 +0x2bea fp=0xc00433df20 sp=0xc00433d890 pc=0xadb06a
main.main()
        /usr/lib/go/src/cmd/compile/main.go:51 +0x96 fp=0xc00433df98 sp=0xc00433df20 pc=0xbf7856 
runtime.main() 
        /usr/lib/go/src/runtime/proc.go:201 +0x207 fp=0xc00433dfe0 sp=0xc00433df98 pc=0x42c367 
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00433dfe8 sp=0xc00433dfe0 pc=0x457ae1
```

**Expected behavior**
It should be able to compile itself without excess amounts of memory.

**Environment (please complete the following information):**
 - OS: archlinux x64

**Comment by 42wim** [comment]
Did some tests myself, seems that you need 450MB at the moment to compile (with go1.11)
This is not something I can fix. 

If you don't have enough memory, you can use the binary releases.

Any ideas or a PR on how to fix the memory problem are welcome.

**Comment by southerntofu** [comment]
Hello, i was previously compiling fine in 2GB memory system, but now latest releases fail to compile. Maybe it would be nice to track build memory usage in CI to prevent further "regressions" ?

**Comment by 42wim** [comment]
It's not a regression, the more bridges supported/code the more memory is needed.
See https://github.com/42wim/matterbridge/pull/1054 for how to exclude bridges you don't need.

**Comment by southerntofu** [comment]
Thanks for that link that's exactly what i was looking for. Would you accept a PR to add a note about it in the README?

Also, I'm not very experienced with go, but isn't there ways to rearchitecture the code so it takes less RAM to build? i'm thinking if every bridge has its own package (instead of a single bridgemap package) maybe it would be smoother?
