### ISSUE TITLE
compile(?) error when running go get on debian

### ISSUE THREAD

**Issue by ftyers** [42wim/matterbridge#568]
**Describe the bug**
Mattermostbridge won't compile(?)

**To Reproduce**
```
spectre@ilazki:~/local$ go get github.com/42wim/matterbridge
# github.com/42wim/matterbridge/vendor/github.com/lrstanley/girc
src/github.com/42wim/matterbridge/vendor/github.com/lrstanley/girc/client.go:493: undefined: sort.Slice
src/github.com/42wim/matterbridge/vendor/github.com/lrstanley/girc/client.go:526: undefined: sort.Slice
# github.com/42wim/matterbridge/vendor/github.com/mattermost/platform/model
src/github.com/42wim/matterbridge/vendor/github.com/mattermost/platform/model/post_list.go:87: undefined: sort.Slice
# github.com/42wim/matterbridge/vendor/github.com/matterbridge/gozulipbot
src/github.com/42wim/matterbridge/vendor/github.com/matterbridge/gozulipbot/queue.go:47: undefined: time.Until
src/github.com/42wim/matterbridge/vendor/github.com/matterbridge/gozulipbot/queue.go:50: undefined: time.Until
src/github.com/42wim/matterbridge/vendor/github.com/matterbridge/gozulipbot/queue.go:67: undefined: time.Until
src/github.com/42wim/matterbridge/vendor/github.com/matterbridge/gozulipbot/queue.go:95: undefined: time.Until
src/github.com/42wim/matterbridge/vendor/github.com/matterbridge/gozulipbot/queue.go:98: undefined: time.Until
src/github.com/42wim/matterbridge/vendor/github.com/matterbridge/gozulipbot/queue.go:115: undefined: time.Until
```

**Environment (please complete the following information):**

```
spectre@ilazki:~/local$ cat /etc/issue
Debian GNU/Linux 9 \n \l
```

**Comment by 42wim** [comment]
I think your go version is maybe too old.
What is output of `go version`?

**Comment by ftyers** [comment]
```
$ go version
go version go1.7.4 linux/386
```

**Comment by ftyers** [comment]
Now I get:
```
spectre@ilazki:~/local$ echo $GOPATH
/home/spectre/local
spectre@ilazki:~/local$ go get github.com/42wim/matterbridge
spectre@ilazki:~/local$ ls
bin  include  lib  pkg  share  src
```

e.g. no output. Any thoughts?

**Comment by ftyers** [comment]
Now I'm getting:
```
spectre@ilazki:~/local/etc$ ../bin/matterbridge 
[2018-11-08T13:21:09Z]  INFO main:         Running version 1.11.4-dev 
[2018-11-08T13:21:09Z]  INFO main:         WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x871948f]

goroutine 1 [running]:
github.com/42wim/matterbridge/gateway.(*Gateway).AddBridge(0x1b58aae0, 0x1b4a3d44, 0x0, 0x0)
	/home/spectre/local/src/github.com/42wim/matterbridge/gateway/gateway.go:115 +0x30f
github.com/42wim/matterbridge/gateway.(*Gateway).AddConfig(0x1b58aae0, 0x1b58aab0, 0x0, 0x0)
	/home/spectre/local/src/github.com/42wim/matterbridge/gateway/gateway.go:127 +0x1ae
github.com/42wim/matterbridge/gateway.New(0x1b594150, 0x9, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1b3a5bd0, ...)
	/home/spectre/local/src/github.com/42wim/matterbridge/gateway/gateway.go:82 +0xf6
github.com/42wim/matterbridge/gateway.NewRouter(0x1b4efba0, 0x11, 0x1b4efba0, 0x1)
	/home/spectre/local/src/github.com/42wim/matterbridge/gateway/router.go:34 +0x1c3
main.main()
	/home/spectre/local/src/github.com/42wim/matterbridge/matterbridge.go:48 +0x460
spectre@ilazki:~/local/etc$ ls
matterbridge.toml
```

Here is the config file:
```
spectre@ilazki:~/local/etc$ cat matterbridge.toml 
[irc]
    [irc.freenode]
    Server="irc.freenode.net:6667"
    Nick="zubia"

[mattermost]
    [chat.mycroft.ai]
    Server="chat.mycroft.ai"
    Team="Mycroft"
    Login="xxx"
    Password="xxx"
    PrefixMessagesWithNick=true
    RemoteNickFormat="[{PROTOCOL}] <{NICK}> "

[[gateway]]
name="mygateway"
enable=true
    [[gateway.inout]]
    account="irc.freenode"
    channel="#mycroft"

    [[gateway.inout]]
    account="chat.mycroft.ai"
    channel="general"

```

**Comment by 42wim** [comment]
`[chat.mycroft.ai]` should be replaced by `[mattermost.mycroft.ai]` everywhere

**Comment by ftyers** [comment]
Done that, now I get:

```
spectre@ilazki:~/local$ ./bin/matterbridge -conf etc/matterbridge.toml -debug
[0000]  INFO main:         Enabling debug
[0000]  INFO main:         Running version 1.11.4-dev 
[0000]  INFO main:         WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
[0000]  INFO gateway:      Parsing gateway mygateway
[0000]  INFO gateway:      Starting bridge: irc.freenode 
[0000]  INFO irc:          Connecting irc.freenode.net:6667
[0000] DEBUG irc:          "CLIENT_INIT :irc.freenode.net:6667"
[0000] DEBUG irc:          ":verne.freenode.net NOTICE * :*** Looking up your hostname..."
[0000] DEBUG irc:          ":verne.freenode.net NOTICE * :*** Checking Ident"
[0000] DEBUG irc:          ":verne.freenode.net NOTICE * :*** No Ident response"
[0000] DEBUG irc:          ":verne.freenode.net NOTICE * :*** Found your hostname"
[0000] DEBUG irc:          ":verne.freenode.net CAP * LS :account-notify extended-join identify-msg multi-prefix sasl"
[0000] DEBUG irc:          ":verne.freenode.net CAP zubia ACK :account-notify extended-join multi-prefix "
[0000] DEBUG irc:          ":verne.freenode.net 001 zubia :Welcome to the freenode Internet Relay Chat Network zubia"
[0000] DEBUG irc:          "CLIENT_GENERAL_UPDATED"
[0000] DEBUG irc:          Registering callbacks
[0000]  INFO irc:          Connection succeeded
[0000]  INFO bridge:       irc.freenode: joining #mycroft (ID: #mycroftirc.freenode)
[0000]  INFO gateway:      Starting bridge: mattermost.mycroft.ai 
[0000]  INFO mattermost:   Connecting using login/password (sending and receiving)
[0000]  INFO mattermost:   Connecting harglebargle@mailinator.com (team: Mycroft) on mattermost.mycroft.ai
[0000] DEBUG irc:          handleJoinPart: empty Params? girc.Event{Source:(*girc.Source)(0x19f80a60), Tags:girc.Tags(nil), Timestamp:time.Time{wall:0xbef12d612bb8ba39, ext:325734137, loc:(*time.Location)(0x9019ae0)}, Command:"QUIT", Params:[]string(nil), Trailing:"K-Lined", EmptyTrailing:false, Sensitive:false, Echo:false}
[0000] ERROR irc:          disconnect: error: EOF
[0000]  INFO irc:          reconnecting in 30 seconds...
[0000] FATAL main:         Starting gateway failed: Bridge mattermost.mycroft.ai failed to start: "https://mattermost.mycroft.ai/api/v4/users/logout: model.client.connecting.app_error, Post https://mattermost.mycroft.ai/api/v4/users/logout: dial tcp: lookup mattermost.mycroft.ai on 80.68.80.24:53: no such host"
```

**Comment by 42wim** [comment]
of course the address of your server stays the same

**Comment by ftyers** [comment]
Ah ok, I missed the []... now It seems to work, thanks! :)

**Comment by 42wim** [comment]
Add `DebugLevel=1` under `[irc.freenode]`

**Comment by ftyers** [comment]
```
[irc]
    [irc.freenode]
    Server="irc.freenode.net:6667"
    Nick="zubiak"
    NickServNick="Nickserv"
    NickServPassword="xxx"
    RemoteNickFormat="<{NICK}> "
    DebugLevel=1
```

And from the logs:

```
[0003] DEBUG irc:          ":zubiak MODE zubiak :+Ri"
[0003] DEBUG irc:          ":NickServ!NickServ@services. NOTICE zubiak :This nickname is registered. Please choose a different nickname, or identify via \x02/msg NickServ identify <password>\x02."
[0003] DEBUG irc:          ":freenode-connect!frigg@freenode/utility-bot/frigg NOTICE zubiak :Due to the persistent ongoing spam, all new connections are being set +R (block messages from unidentified users) and will be scanned for vulnerabilities. This will not harm your computer, and vulnerable hosts will be notified."
[0003] DEBUG irc:          ":freenode-connect!frigg@freenode/utility-bot/frigg PRIVMSG zubiak :\x01VERSION\x01"
[0005] DEBUG irc:          "CLIENT_CONNECTED :irc.freenode.net:6667"
[0009] DEBUG irc:          ":wilhelm.freenode.net 477 zubiak #mycroft :Cannot join channel (+r) - you need to be identified with services - see https://freenode.net/kb/answer/registration"
```

**Comment by 42wim** [comment]
Try using SASL, see https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample#L25-L28
