### ISSUE TITLE
telegram: nil pointer dereference panic on message receive

### ISSUE THREAD

**Issue by WGH-** [42wim/matterbridge#620]
Telegram bridge crashes on message reception with nil pointer dereference. This is isn't random, and happens on every message.

```
[0433] DEBUG telegram:     == Receiving event: &tgbotapi.Message{MessageID:19, From:(*tgbotapi.User)(0xc000686000), Date:1543494704, Chat:(*tgbotapi.Chat)(0xc0008f4000), ForwardFrom:(*tgbotapi.User)(nil), ForwardFromChat:(*tgbotapi.Chat)(nil), ForwardFromMessageID:0, ForwardDate:0, ReplyToMessage:(*tgbotapi.Message)(nil), EditDate:0, Text:"test тест", Entities:(*[]tgbotapi.MessageEntity)(nil), Audio:(*tgbotapi.Audio)(nil), Document:(*tgbotapi.Document)(nil), Animation:(*tgbotapi.ChatAnimation)(nil), Game:(*tgbotapi.Game)(nil), Photo:(*[]tgbotapi.PhotoSize)(nil), Sticker:(*tgbotapi.Sticker)(nil), Video:(*tgbotapi.Video)(nil), VideoNote:(*tgbotapi.VideoNote)(nil), Voice:(*tgbotapi.Voice)(nil), Caption:"", Contact:(*tgbotapi.Contact)(nil), Location:(*tgbotapi.Location)(nil), Venue:(*tgbotapi.Venue)(nil), NewChatMembers:(*[]tgbotapi.User)(nil), LeftChatMember:(*tgbotapi.User)(nil), NewChatTitle:"", NewChatPhoto:(*[]tgbotapi.PhotoSize)(nil), DeleteChatPhoto:false, GroupChatCreated:false, SuperGroupChatCreated:false, ChannelChatCreated:false, MigrateToChatID:0, MigrateFromChatID:0, PinnedMessage:(*tgbotapi.Message)(nil), Invoice:(*tgbotapi.Invoice)(nil), SuccessfulPayment:(*tgbotapi.SuccessfulPayment)(nil), PassportData:(*tgbotapi.PassportData)(nil)}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb6ae29]

goroutine 27 [running]:
github.com/42wim/matterbridge/bridge/telegram.(*Btelegram).handleRecv(0xc00052fa00, 0xc0005a6120)
        /tmp/mattbridge_test/go/src/github.com/42wim/matterbridge/bridge/telegram/handlers.go:128 +0x249
created by github.com/42wim/matterbridge/bridge/telegram.(*Btelegram).Connect
        /tmp/mattbridge_test/go/src/github.com/42wim/matterbridge/bridge/telegram/telegram.go:46 +0x2fd
```
- Linux
- version: 1.12.1-dev
- fc5e3a672862e53192dadfd9689dad766772aeea

Config:
```
[mattermost]
[mattermost.XXX_matt]
WebhookURL="https://matt.XXX/hooks/<redacted>"
WebhookBindAddress="<redacted>:9999"

[telegram]
[telegram.XXX_tg]
Token="redacted"

[[gateway]]
name="XXX"
enable=true
    [[gateway.inout]]
    account="mattermost.XXX_matt"
    channel="#telegram"

    [[gateway.inout]]
    account="telegram.XXX_tg"
    channel="-<redacted>"
```

**Comment by WGH-** [comment]
Odd, I've recompiled matterbridge using latest release, and even though none of the commits since fc5e3a6 touched any telegram code, it's no longer crashing.

**Comment by WGH-** [comment]
Or maybe it did: https://github.com/42wim/matterbridge/compare/fc5e3a6..v1.12.1

Anyway, master was broken less than 24h ago.

**Comment by WGH-** [comment]
Hmmm, no, I don't get it. master seems to be very out of sync with the latest release: https://github.com/42wim/matterbridge/compare/master..v1.12.1

And current master still crashes.

**Comment by 42wim** [comment]
Yes, only bugfixes are in release-1.12
I did some refactoring with telegram on master which are not included in stable.
Could you retry from current master (i don't have telegram to test myself)

**Comment by WGH-** [comment]
The crash is fixed and messages are forwarded from telegram correctly.

**Comment by 42wim** [comment]
Thanks for the feedback!
