### ISSUE TITLE
Random high CPU usage

### ISSUE THREAD

**Issue by taoeffect** [42wim/matterbridge#68]
Per [your request](https://github.com/42wim/matterbridge/issues/55#issuecomment-256184897), I caught it spinning up the CPU to ~50% of 4 cores (meaning fully using about 2 cores), and I got the stack trace (via `journalctl -u matterbridge`) after running `kill -ABRT <pid>`.

```
SIGABRT: abort
PC=0x45ae21 m=0
goroutine 0 [idle]:
runtime.futex(0xbbf3d0, 0x0, 0x0, 0x0, 0x0, 0x7ffd00000001, 0x0, 0x0, 0x7ffd6d538840, 0x40ece2, ...)
/usr/local/go/src/runtime/sys_linux_amd64.s:387 +0x21
runtime.futexsleep(0xbbf3d0, 0x0, 0xffffffffffffffff)
/usr/local/go/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0xbbf3d0)
/usr/local/go/src/runtime/lock_futex.go:145 +0x82
runtime.stopm()
/usr/local/go/src/runtime/proc.go:1594 +0xad
runtime.findrunnable(0xc420014000, 0x0)
/usr/local/go/src/runtime/proc.go:2021 +0x228
runtime.schedule()
/usr/local/go/src/runtime/proc.go:2120 +0x14c
runtime.park_m(0xc4201969c0)
/usr/local/go/src/runtime/proc.go:2183 +0x123
runtime.mcall(0x7ffd6d5389e0)
/usr/local/go/src/runtime/asm_amd64.s:240 +0x5b
goroutine 1 [select (no cases), 4529 minutes]:
main.main()
/home/username/gohome/src/github.com/42wim/matterbridge/matterbridge.go:59 +0x3de
goroutine 17 [syscall, 4529 minutes, locked to thread]:
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
goroutine 20 [chan receive, 4529 minutes]:
github.com/42wim/matterbridge/vendor/github.com/alecthomas/log4go.(*ConsoleLogWriter).run(0xc4200d8700, 0xb99080, 0xc420076008)
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/github.com/alecthomas/log4go/termlog.go:33 +0x62
created by github.com/42wim/matterbridge/vendor/github.com/alecthomas/log4go.NewConsoleLogWriter
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/github.com/alecthomas/log4go/termlog.go:26 +0xbf
goroutine 21 [chan receive, 4529 minutes]:
github.com/42wim/matterbridge/gateway.(*Gateway).handleReceive(0xc4205c5d70, 0xc42006ccc0)
/home/username/gohome/src/github.com/42wim/matterbridge/gateway/gateway.go:60 +0x87
github.com/42wim/matterbridge/gateway.New(0xc42006cae0, 0xc42006b3b0, 0x0, 0x0)
/home/username/gohome/src/github.com/42wim/matterbridge/gateway/gateway.go:53 +0xb07
main.main.func2(0xc42006cae0, 0xc42011ba10, 0x8, 0x1, 0xc42006ffc0, 0x2, 0x2, 0xc42006ff40, 0x2, 0x2)
/home/username/gohome/src/github.com/42wim/matterbridge/matterbridge.go:53 +0x82
created by main.main
/home/username/gohome/src/github.com/42wim/matterbridge/matterbridge.go:57 +0x4c2
goroutine 22 [select]:
github.com/42wim/matterbridge/vendor/github.com/nlopes/slack.(*RTM).handleEvents(0xc42014ed80, 0xc4201a6000, 0x6fc23ac00)
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/github.com/nlopes/slack/websocket_managed_conn.go:148 +0x399
github.com/42wim/matterbridge/vendor/github.com/nlopes/slack.(*RTM).ManageConnection(0xc42014ed80)
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/github.com/nlopes/slack/websocket_managed_conn.go:53 +0x1d3
created by github.com/42wim/matterbridge/bridge/slack.(*Bslack).Connect
/home/username/gohome/src/github.com/42wim/matterbridge/bridge/slack/slack.go:60 +0x61d
goroutine 23 [chan receive, 4529 minutes]:
github.com/42wim/matterbridge/bridge/slack.(*Bslack).handleSlack(0xc42012b420)
/home/username/gohome/src/github.com/42wim/matterbridge/bridge/slack/slack.go:150 +0x230
created by github.com/42wim/matterbridge/bridge/slack.(*Bslack).Connect
/home/username/gohome/src/github.com/42wim/matterbridge/bridge/slack/slack.go:63 +0x278
goroutine 24 [chan receive]:
github.com/42wim/matterbridge/bridge/slack.(*Bslack).handleSlackClient(0xc42012b420, 0xc42006cf60)
/home/username/gohome/src/github.com/42wim/matterbridge/bridge/slack/slack.go:161 +0xbb
created by github.com/42wim/matterbridge/bridge/slack.(*Bslack).handleSlack
/home/username/gohome/src/github.com/42wim/matterbridge/bridge/slack/slack.go:144 +0x14e
goroutine 83 [chan receive, 4529 minutes]:
github.com/42wim/matterbridge/bridge/gitter.(*Bgitter).JoinChannel.func1(0xc42006b4a0, 0xc4203e48a0, 0xc420150680, 0x16)
/home/username/gohome/src/github.com/42wim/matterbridge/bridge/gitter/gitter.go:68 +0x90
created by github.com/42wim/matterbridge/bridge/gitter.(*Bgitter).JoinChannel
/home/username/gohome/src/github.com/42wim/matterbridge/bridge/gitter/gitter.go:81 +0x2cd
goroutine 82 [runnable]:
github.com/42wim/matterbridge/vendor/github.com/sromku/go-gitter.(*Gitter).Listen(0xc420466550, 0xc4203e48a0)
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/github.com/sromku/go-gitter/stream.go:58 +0x6e9
created by github.com/42wim/matterbridge/bridge/gitter.(*Bgitter).JoinChannel
/home/username/gohome/src/github.com/42wim/matterbridge/bridge/gitter/gitter.go:64 +0x284
goroutine 55 [IO wait]:
net.runtime_pollWait(0x7f65edcd0cf0, 0x72, 0x7)
/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4201940d0, 0x72, 0xc420033918, 0xc4200700a0)
/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4201940d0, 0xb9ad40, 0xc4200700a0)
/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420194070, 0xc420565000, 0x1000, 0x1000, 0x0, 0xb9ad40, 0xc4200700a0)
/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc4201a4008, 0xc420565000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/usr/local/go/src/net/net.go:173 +0x70
crypto/tls.(*block).readFromUntil(0xc420495380, 0x7f65edc90028, 0xc4201a4008, 0x5, 0xc4201a4008, 0x0)
/usr/local/go/src/crypto/tls/conn.go:472 +0x91
crypto/tls.(*Conn).readRecord(0xc4203f0a80, 0x9ad917, 0xc4203f0b80, 0x4ecc01)
/usr/local/go/src/crypto/tls/conn.go:574 +0xc4
crypto/tls.(*Conn).Read(0xc4203f0a80, 0xc42046e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/usr/local/go/src/crypto/tls/conn.go:1109 +0x116
bufio.(*Reader).fill(0xc42018e120)
/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadByte(0xc42018e120, 0xc420467130, 0x2, 0xc420033d38)
/usr/local/go/src/bufio/bufio.go:231 +0x51
github.com/42wim/matterbridge/vendor/golang.org/x/net/websocket.hybiFrameReaderFactory.NewFrameReader(0xc42018e120, 0x9ad950, 0xc4200a8028, 0xbdcad0, 0xc42049c060)
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/golang.org/x/net/websocket/hybi.go:123 +0x5d
github.com/42wim/matterbridge/vendor/golang.org/x/net/websocket.Codec.Receive(0x9acf98, 0x9acfa0, 0xc4200a8000, 0x8de100, 0xc42049c060, 0x0, 0x0)
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/golang.org/x/net/websocket/websocket.go:314 +0xb2
github.com/42wim/matterbridge/vendor/github.com/nlopes/slack.(*RTM).receiveIncomingEvent(0xc42014ed80)
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/github.com/nlopes/slack/websocket_managed_conn.go:242 +0xc4
github.com/42wim/matterbridge/vendor/github.com/nlopes/slack.(*RTM).handleIncomingEvents(0xc42014ed80, 0xc4201a6000)
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/github.com/nlopes/slack/websocket_managed_conn.go:189 +0x57
created by github.com/42wim/matterbridge/vendor/github.com/nlopes/slack.(*RTM).ManageConnection
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/github.com/nlopes/slack/websocket_managed_conn.go:50 +0x1a9
rax    0xca
rbx    0xbbe730
rcx    0xffffffffffffffff
rdx    0x0
rdi    0xbbf3d0
rsi    0x0
rbp    0x7ffd6d538810
rsp    0x7ffd6d5387c8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x0
r13    0xc420196680
r14    0x43ec50
r15    0xa119d0
rip    0x45ae21
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

This is using build manually installed via `go install` from commit 96620a3.

**Comment by 42wim** [comment]
That was interesting. Should be fixed now, but let me know if it isn't ;-)

**Comment by taoeffect** [comment]
Awesome, thanks! Will definitely let you know if I notice anything again. Thanks again!! ^_^
