### ISSUE TITLE
sigsegv When the given protocol doesn't exist

### ISSUE THREAD

**Issue by KrzysztofMadejski** [42wim/matterbridge#739]
When the given protocol doesn't exist. A more informative error would be welcomed.

```
[0000]  INFO main:         Enabling debug
[0000]  INFO main:         Running version 1.13.2-dev 
[0000]  INFO main:         WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x90ecae]

goroutine 1 [running]:
github.com/42wim/matterbridge/gateway.(*Gateway).AddBridge(0xc00051c1e0, 0xc0004e98c8, 0x2, 0x2)
	/home/kmadejski/Projects/42matterbridge/gateway/gateway.go:83 +0x3de
github.com/42wim/matterbridge/gateway.(*Gateway).AddConfig(0xc00051c1e0, 0xc00051c0c0, 0x0, 0x0)
	/home/kmadejski/Projects/42matterbridge/gateway/gateway.go:98 +0x367
github.com/42wim/matterbridge/gateway.New(0xc000426ef8, 0x8, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0003b2510, ...)
	/home/kmadejski/Projects/42matterbridge/gateway/gateway.go:47 +0x20a
github.com/42wim/matterbridge/gateway.NewRouter(0x11a9720, 0xc0004c0270, 0xc000444f60, 0xc0004c0270, 0x1, 0x2)
	/home/kmadejski/Projects/42matterbridge/gateway/router.go:44 +0x368
main.main()
	/home/kmadejski/Projects/42matterbridge/matterbridge.go:52 +0x54b
```

**Comment by KrzysztofMadejski** [comment]
Thank you!
