### ISSUE TITLE
NickFormat get's doubled by the NICK

### ISSUE THREAD

**Issue by jlsjonas** [42wim/matterbridge#77]
RemoteNickFormat's {NICK} seems to double the entire nickformat:
`[{PROTOCOL}] <{NICK}>` becomes
`[protocol] <[protocol] <username>>`

**Comment by 42wim** [comment]
could you paste your config?

**Comment by jlsjonas** [comment]
slightly modified sample config (the api details & channels)
only using the samechannelgateway at the moment though

**Comment by jlsjonas** [comment]
🤔 just did a `go get` to confirm and I'm still experiencing this issue

**Comment by 42wim** [comment]
try ```go get -u```

**Comment by jlsjonas** [comment]
no time to debug at the moment but I got following error after updating the binary (on the same config that's working "in production" now:
```

INFO[2016-11-21T17:34:54Z] Connecting matterbridge (team: wazetest) on mattermost.tomputtemans.com  module=mattermost
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x59d058]

goroutine 6 [running]:
panic(0x902100, 0xc42000c0f0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/42wim/matterbridge/matterclient.(*MMClient).initUser(0xc4200899e0, 0x0, 0x0)
        /root/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:625 +0x1e8
github.com/42wim/matterbridge/matterclient.(*MMClient).Login(0xc4200899e0, 0x99ab41, 0x1e)
        /root/go/src/github.com/42wim/matterbridge/matterclient/matterclient.go:148 +0xa1e
github.com/42wim/matterbridge/bridge/mattermost.(*Bmattermost).Connect(0xc42011f500, 0xc420172420, 0xc42010be80)
        /root/go/src/github.com/42wim/matterbridge/bridge/mattermost/mattermost.go:68 +0x27f
github.com/42wim/matterbridge/gateway/samechannel.New(0xc4200e4700, 0xc42001dd60, 0x0, 0x0)
        /root/go/src/github.com/42wim/matterbridge/gateway/samechannel/samechannel.go:33 +0x3ce
main.main.func1(0xc4200e4700, 0x0, 0x0, 0x1, 0xc420089830, 0x9, 0x9, 0xc42015e690, 0x3, 0x3)
        /root/go/src/github.com/42wim/matterbridge/matterbridge.go:40 +0x82
created by main.main
        /root/go/src/github.com/42wim/matterbridge/matterbridge.go:44 +0x827
```
