### ISSUE TITLE
[Rocketchat] 500 on sending messages using API

### ISSUE THREAD

**Issue by iprok** [42wim/matterbridge#773]
**Describe the bug**
We have telegram <-> rocketchat inout gateway. Messages to rocketchat->telegram go OK. Messages telegram->rocketchat doesn't go at all resulting 500 error: "Exception while invoking method 'sendMessage' Error: The 'rid' property on the message object is missing." in rocketchat logs.

**To Reproduce**
Use matterbridge 1.14.1 and rocketchat 0.74.3. Make bridge telegram->rocketchat. Try to send message.

**Expected behavior**
Messages go successfully telegram<->rocketchat

**Screenshots/debug logs**
Matterbridge log:
[0000]  INFO main:         Gateway(s) started succesfully. Now relaying messages
[0023] DEBUG telegram:     == Receiving event: &tgbotapi.Message{MessageID:1197, From:(*tgbotapi.User)(0xc000635a90), Date:1553450779, Chat:(*tgbotapi.Chat)(0xc0007d86c0), ForwardFrom:(*tgbotapi.User)(nil), ForwardFromChat:(*tgbotapi.Chat)(nil), ForwardFromMessageID:0, ForwardDate:0, ReplyToMessage:(*tgbotapi.Message)(nil), EditDate:0, Text:"yyy", Entities:(*[]tgbotapi.MessageEntity)(nil), Audio:(*tgbotapi.Audio)(nil), Document:(*tgbotapi.Document)(nil), Animation:(*tgbotapi.ChatAnimation)(nil), Game:(*tgbotapi.Game)(nil), Photo:(*[]tgbotapi.PhotoSize)(nil), Sticker:(*tgbotapi.Sticker)(nil), Video:(*tgbotapi.Video)(nil), VideoNote:(*tgbotapi.VideoNote)(nil), Voice:(*tgbotapi.Voice)(nil), Caption:"", Contact:(*tgbotapi.Contact)(nil), Location:(*tgbotapi.Location)(nil), Venue:(*tgbotapi.Venue)(nil), NewChatMembers:(*[]tgbotapi.User)(nil), LeftChatMember:(*tgbotapi.User)(nil), NewChatTitle:"", NewChatPhoto:(*[]tgbotapi.PhotoSize)(nil), DeleteChatPhoto:false, GroupChatCreated:false, SuperGroupChatCreated:false, ChannelChatCreated:false, MigrateToChatID:0, MigrateFromChatID:0, PinnedMessage:(*tgbotapi.Message)(nil), Invoice:(*tgbotapi.Invoice)(nil), SuccessfulPayment:(*tgbotapi.SuccessfulPayment)(nil), PassportData:(*tgbotapi.PassportData)(nil)}
[0024] DEBUG telegram:     <= Sending message from I on telegram.k to gateway
[0024] DEBUG telegram:     <= Message is config.Message{Text:"yyy", Channel:"-284", Username:"I", UserID:"53", Avatar:"", Account:"telegram.k", Event:"", Protocol:"", Gateway:"", ParentID:"", Timestamp:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, ID:"1197", Extra:map[string][]interface {}{}}
[0024] DEBUG gateway:      => Sending config.Message{Text:"yyy", Channel:"-284", Username:"I", UserID:"53", Avatar:"", Account:"telegram.k", Event:"", Protocol:"", Gateway:"test", ParentID:"", Timestamp:time.Time{wall:0xbf1e0fa6dbb287bf, ext:24019399900, loc:(*time.Location)(0x1d1a440)}, ID:"1197", Extra:map[string][]interface {}{}} from telegram.k (-284) to rocketchat.t (#2li)
[0024] ERROR gateway:      SendMessage failed: {"error":500,"errorType":"Meteor.Error","isClientSafe":true,"message":"Internal server error [500]","reason":"Internal server error"}

Rocketchat logs:
[34mI20190324-18:06:19.496(0) Exception while invoking method 'sendMessage' Error: The 'rid' property on the message object is missing.     at MethodInvocation.sendMessage (packages/rocketchat:lib/server/methods/sendMessage.js:18:10)     at MethodInvocation.methodsMap.(anonymous function) (packages/rocketchat:lib/server/lib/debug.js:71:34)     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)     at Promise (packages/ddp-server/livedata_server.js:715:46)     at new Promise (<anonymous>)     at Session.method (packages/ddp-server/livedata_server.js:689:23)     at packages/ddp-server/livedata_server.js:559:43 

**Environment (please complete the following information):**
 - OS: Linux amd64
 - Matterbridge version: 1.14.1

**Comment by iprok** [comment]
And I've just seen https://github.com/42wim/matterbridge/tree/fix-rocketchat-channel , removed '#' from channel names in rocketchat and it has started to work.

**Comment by 42wim** [comment]
Was still a valid issue :)
