### ISSUE TITLE
irc: panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by Bluscream** [42wim/matterbridge#785]
**Describe the bug**
```
[2019-04-02T22:42:07+02:00]  INFO main:         Running version 1.14.2-dev
[2019-04-02T22:42:07+02:00]  INFO main:         WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
[2019-04-02T22:42:07+02:00]  INFO router:       Parsing gateway Ayano
[2019-04-02T22:42:07+02:00]  INFO router:       Starting bridge: discord.ayano
[2019-04-02T22:42:07+02:00]  INFO discord:      Connecting
[2019-04-02T22:42:07+02:00]  INFO discord:      Connecting using token
[2019-04-02T22:42:07+02:00]  INFO discord:      Connection succeeded
[2019-04-02T22:42:09+02:00]  INFO discord:      discord.ayano: joining ID:562226543590375436 (ID: ID:562226543590375436discord.ayano)
[2019-04-02T22:42:09+02:00]  INFO router:       Starting bridge: irc.twitch
[2019-04-02T22:42:09+02:00]  INFO irc:          Connecting irc.chat.twitch.tv:6697
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/42wim/matterbridge/bridge/irc.(*Birc).getClient(0x2e808a0, 0x4, 0xb0a294, 0xd)
        /home/blu/go/src/github.com/42wim/matterbridge/bridge/irc/irc.go:238 +0x33c
github.com/42wim/matterbridge/bridge/irc.(*Birc).Connect(0x2e808a0, 0x4, 0xb18bd8)
        /home/blu/go/src/github.com/42wim/matterbridge/bridge/irc/irc.go:73 +0xfc
github.com/42wim/matterbridge/gateway.(*Router).Start(0x2e45a00, 0xe01ae8, 0x2e80690)
        /home/blu/go/src/github.com/42wim/matterbridge/gateway/router.go:70 +0x29c
main.main()
        /home/blu/go/src/github.com/42wim/matterbridge/matterbridge.go:57 +0x3bc
```

**To Reproduce**
Steps to reproduce the behavior: No idea what I did wrong

**Expected behavior**
Normal start and relay

**Screenshots/debug logs**
```
blu@minopia:~/go/bin $ ./matterbridge -debug
[0000]  INFO main:         Enabling debug logging.
[0000]  INFO main:         Running version 1.14.2-dev
[0000]  INFO main:         WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
[0000]  INFO router:       Parsing gateway Ayano
[0000]  INFO router:       Starting bridge: discord.ayano
[0000]  INFO discord:      Connecting
[0000]  INFO discord:      Connecting using token
[0000]  INFO discord:      Connection succeeded
[0001] DEBUG discord:      found channel &discordgo.Channel{ID:"494877207320330290", GuildID:"494877206758031363", Name:"Text-Kanäle", Topic:"", Type:4, LastMessageID:"", NSFW:false, Icon:"", Position:0, Bitrate:0, Recipients:[]*discordgo.User(nil), Messages:[]*discordgo.Message(nil), PermissionOverwrites:[]*discordgo.PermissionOverwrite{}, UserLimit:0, ParentID:""}
[0001] DEBUG discord:      found channel &discordgo.Channel{ID:"494877207320330291", GuildID:"494877206758031363", Name:"chat", Topic:"", Type:0, LastMessageID:"562722716893970443", NSFW:false, Icon:"", Position:0, Bitrate:0, Recipients:[]*discordgo.User(nil), Messages:[]*discordgo.Message(nil), PermissionOverwrites:[]*discordgo.PermissionOverwrite{}, UserLimit:0, ParentID:"494877207320330290"}
[0001] DEBUG discord:      found channel &discordgo.Channel{ID:"494877207320330292", GuildID:"494877206758031363", Name:"Sprach-Kanäle", Topic:"", Type:4, LastMessageID:"", NSFW:false, Icon:"", Position:2, Bitrate:0, Recipients:[]*discordgo.User(nil), Messages:[]*discordgo.Message(nil), PermissionOverwrites:[]*discordgo.PermissionOverwrite{}, UserLimit:0, ParentID:""}
[0001] DEBUG discord:      found channel &discordgo.Channel{ID:"494877207320330293", GuildID:"494877206758031363", Name:"Talk1", Topic:"", Type:2, LastMessageID:"", NSFW:false, Icon:"", Position:0, Bitrate:64000, Recipients:[]*discordgo.User(nil), Messages:[]*discordgo.Message(nil), PermissionOverwrites:[]*discordgo.PermissionOverwrite{}, UserLimit:0, ParentID:"494877207320330292"}
[0001] DEBUG discord:      found channel &discordgo.Channel{ID:"494877390489649163", GuildID:"494877206758031363", Name:"bilder-videos-gifs", Topic:"", Type:0, LastMessageID:"562651359896272908", NSFW:false, Icon:"", Position:1, Bitrate:0, Recipients:[]*discordgo.User(nil), Messages:[]*discordgo.Message(nil), PermissionOverwrites:[]*discordgo.PermissionOverwrite{}, UserLimit:0, ParentID:"494877207320330290"}
[0001] DEBUG discord:      found channel &discordgo.Channel{ID:"494877551341076480", GuildID:"494877206758031363", Name:"unter 4 augen", Topic:"", Type:2, LastMessageID:"", NSFW:false, Icon:"", Position:1, Bitrate:64000, Recipients:[]*discordgo.User(nil), Messages:[]*discordgo.Message(nil), PermissionOverwrites:[]*discordgo.PermissionOverwrite{}, UserLimit:2, ParentID:"494877207320330292"}
[0001] DEBUG discord:      found channel &discordgo.Channel{ID:"494877591543611402", GuildID:"494877206758031363", Name:"AFK", Topic:"", Type:2, LastMessageID:"", NSFW:false, Icon:"", Position:2, Bitrate:64000, Recipients:[]*discordgo.User(nil), Messages:[]*discordgo.Message(nil), PermissionOverwrites:[]*discordgo.PermissionOverwrite{}, UserLimit:0, ParentID:"494877207320330292"}
[0001] DEBUG discord:      found channel &discordgo.Channel{ID:"494877628142977044", GuildID:"494877206758031363", Name:"Musik", Topic:"", Type:2, LastMessageID:"", NSFW:false, Icon:"", Position:3, Bitrate:64000, Recipients:[]*discordgo.User(nil), Messages:[]*discordgo.Message(nil), PermissionOverwrites:[]*discordgo.PermissionOverwrite{}, UserLimit:0, ParentID:"494877207320330292"}
[0001] DEBUG discord:      found channel &discordgo.Channel{ID:"494942196668039188", GuildID:"494877206758031363", Name:"bilder-und-tts-spam", Topic:"", Type:0, LastMessageID:"538010747364573189", NSFW:false, Icon:"", Position:2, Bitrate:0, Recipients:[]*discordgo.User(nil), Messages:[]*discordgo.Message(nil), PermissionOverwrites:[]*discordgo.PermissionOverwrite{}, UserLimit:0, ParentID:"494877207320330290"}
[0001] DEBUG discord:      found channel &discordgo.Channel{ID:"513063862312894496", GuildID:"494877206758031363", Name:"Ayanos Channel", Topic:"", Type:2, LastMessageID:"", NSFW:false, Icon:"", Position:4, Bitrate:64000, Recipients:[]*discordgo.User(nil), Messages:[]*discordgo.Message(nil), PermissionOverwrites:[]*discordgo.PermissionOverwrite{(*discordgo.PermissionOverwrite)(0x3a9afa0), (*discordgo.PermissionOverwrite)(0x3a9afc0)}, UserLimit:0, ParentID:"494877207320330292"}
[0001] DEBUG discord:      found channel &discordgo.Channel{ID:"516245882027376659", GuildID:"494877206758031363", Name:"fluffy", Topic:"", Type:0, LastMessageID:"533947076975788054", NSFW:false, Icon:"", Position:3, Bitrate:0, Recipients:[]*discordgo.User(nil), Messages:[]*discordgo.Message(nil), PermissionOverwrites:[]*discordgo.PermissionOverwrite{(*discordgo.PermissionOverwrite)(0x3a9afe0), (*discordgo.PermissionOverwrite)(0x3a9b000), (*discordgo.PermissionOverwrite)(0x3a9b020)}, UserLimit:0, ParentID:"494877207320330290"}
[0001] DEBUG discord:      found channel &discordgo.Channel{ID:"561980606830084096", GuildID:"494877206758031363", Name:"rollen-anfrage", Topic:"", Type:0, LastMessageID:"561986930334760962", NSFW:false, Icon:"", Position:4, Bitrate:0, Recipients:[]*discordgo.User(nil), Messages:[]*discordgo.Message(nil), PermissionOverwrites:[]*discordgo.PermissionOverwrite{}, UserLimit:0, ParentID:"494877207320330290"}
[0001] DEBUG discord:      found channel &discordgo.Channel{ID:"562226543590375436", GuildID:"494877206758031363", Name:"ayano_335", Topic:"", Type:0, LastMessageID:"562713686846865410", NSFW:false, Icon:"", Position:5, Bitrate:0, Recipients:[]*discordgo.User(nil), Messages:[]*discordgo.Message(nil), PermissionOverwrites:[]*discordgo.PermissionOverwrite{(*discordgo.PermissionOverwrite)(0x3a9b040), (*discordgo.PermissionOverwrite)(0x3a9b060), (*discordgo.PermissionOverwrite)(0x3a9b080), (*discordgo.PermissionOverwrite)(0x3a9b0a0), (*discordgo.PermissionOverwrite)(0x3a9b0e0), (*discordgo.PermissionOverwrite)(0x3a9b100), (*discordgo.PermissionOverwrite)(0x3a9b120), (*discordgo.PermissionOverwrite)(0x3a9b140), (*discordgo.PermissionOverwrite)(0x3a9b160), (*discordgo.PermissionOverwrite)(0x3a9b180), (*discordgo.PermissionOverwrite)(0x3a9b1a0)}, UserLimit:0, ParentID:"562724280698404885"}
[0001] DEBUG discord:      found channel &discordgo.Channel{ID:"562531518128324619", GuildID:"494877206758031363", Name:"stream", Topic:"", Type:2, LastMessageID:"", NSFW:false, Icon:"", Position:5, Bitrate:64000, Recipients:[]*discordgo.User(nil), Messages:[]*discordgo.Message(nil), PermissionOverwrites:[]*discordgo.PermissionOverwrite{}, UserLimit:0, ParentID:"494877207320330292"}
[0001] DEBUG discord:      found channel &discordgo.Channel{ID:"562724280698404885", GuildID:"494877206758031363", Name:"twitch", Topic:"", Type:4, LastMessageID:"", NSFW:false, Icon:"", Position:1, Bitrate:0, Recipients:[]*discordgo.User(nil), Messages:[]*discordgo.Message(nil), PermissionOverwrites:[]*discordgo.PermissionOverwrite{(*discordgo.PermissionOverwrite)(0x3a9b1c0), (*discordgo.PermissionOverwrite)(0x3a9b1e0)}, UserLimit:0, ParentID:""}
[0001] DEBUG discord:      found channel &discordgo.Channel{ID:"562724503411490847", GuildID:"494877206758031363", Name:"nyanekogame", Topic:"", Type:0, LastMessageID:"", NSFW:false, Icon:"", Position:6, Bitrate:0, Recipients:[]*discordgo.User(nil), Messages:[]*discordgo.Message(nil), PermissionOverwrites:[]*discordgo.PermissionOverwrite{(*discordgo.PermissionOverwrite)(0x3a9b200), (*discordgo.PermissionOverwrite)(0x3a9b220), (*discordgo.PermissionOverwrite)(0x3a9b240), (*discordgo.PermissionOverwrite)(0x3a9b260), (*discordgo.PermissionOverwrite)(0x3a9b2a0), (*discordgo.PermissionOverwrite)(0x3a9b2c0)}, UserLimit:0, ParentID:"562724280698404885"}
[0001]  INFO discord:      discord.ayano: joining ID:562226543590375436 (ID: ID:562226543590375436discord.ayano)
[0001]  INFO router:       Starting bridge: irc.twitch
[0001]  INFO irc:          Connecting irc.chat.twitch.tv:6697
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/42wim/matterbridge/bridge/irc.(*Birc).getClient(0x3a5a900, 0x4, 0xb0a294, 0xd)
        /home/blu/go/src/github.com/42wim/matterbridge/bridge/irc/irc.go:238 +0x33c
github.com/42wim/matterbridge/bridge/irc.(*Birc).Connect(0x3a5a900, 0x4, 0xb18bd8)
        /home/blu/go/src/github.com/42wim/matterbridge/bridge/irc/irc.go:73 +0xfc
github.com/42wim/matterbridge/gateway.(*Router).Start(0x3a27a40, 0xe01ae8, 0x3a5a6f0)
        /home/blu/go/src/github.com/42wim/matterbridge/gateway/router.go:70 +0x29c
main.main()
        /home/blu/go/src/github.com/42wim/matterbridge/matterbridge.go:57 +0x3bc
You have new mail in /var/mail/blu
```

**Environment (please complete the following information):**
 - OS: raspberry pi 3 model B+
 - Matterbridge version: version: 1.14.2-dev

**Additional context**

```toml
[discord.ayano]
Token=""
Server="494877206758031363"
RemoteNickFormat="`{NICK}`: "

[irc.twitch]
Password="oauth:"
Server="irc.chat.twitch.tv:6697"
UseTLS=true
RemoteNickFormat="[Discord] {NICK}: "
Charset="utf-8"
ColorNicks=true

[[gateway]]
name="Ayano"
enable=true
[[gateway.inout]]
account="discord.ayano"
channel="ID:562226543590375436"
[[gateway.inout]]
account="irc.twitch"
channel="#ayano_335"

[[gateway]]
name="NyaNekoGame"
enable=false
[[gateway.inout]]
account="discord.ayano"
channel="ID:562724503411490847"
[[gateway.inout]]
account="irc.twitch"
channel="#nyanekogame"
```

**Comment by 42wim** [comment]
It's a bug, but you can probably fix this for now be adding a `Nick="yournick"` to `[irc.twitch]`

**Comment by Bluscream** [comment]
Oh, thanks. I removed it because you can't nick yourself on twitch

**Comment by 42wim** [comment]
Fixed in master
