### ISSUE TITLE
[mattermost] Joining new channels on startup causes MatterBridge to fail on MatterMost 5.9.0 and MatterBridge 1.14.2

### ISSUE THREAD

**Issue by JustDolanIt** [42wim/matterbridge#804]
**Describe the bug**
After setting up new MatterBridge gateway with new MatterMost channel and restarting MatterBridge, it fails with segmentation violation, but user is joining the channel

Restart of MatterBridge after this works just fine

**To Reproduce**

* Create new MatterMost channel
* Create inout gateway with this channel
* Restart MatterBridge

**Expected behavior**
MatterBridge should just join channel and work without segmentation violation

**Screenshots/debug logs**
Debug log:
```
# ./matterbridge -debug
[0000]  INFO main:         Enabling debug logging.
[0000]  INFO main:         Running version 1.14.2 e4d73b2
[0000]  INFO router:       Parsing gateway fvkmm-mbmm
[0000]  INFO router:       Parsing gateway fvkmm-fvks
[0000]  INFO router:       Parsing gateway fvkmm-fvktg
[0000]  INFO router:       Starting bridge: mattermost.f
[0000]  INFO mattermost:   Connecting using login/password (sending and receiving)
[0000]  INFO mattermost:   Connecting _bot (team: matterbridge) on example.com:443
[0000]  INFO matterclient: Found version 5.9.0.5.9.0.b48f19cb0842a90f72c20c47431608a2.false
[0003]  INFO mattermost:   Connection succeeded
[0003]  INFO mattermost:   mattermost.f2: joining test (ID: testmattermost.f2)
[0003]  INFO router:       Starting bridge: mattermost.f
[0003]  INFO mattermost:   Connecting using login/password (sending and receiving)
[0003] DEBUG mattermost:   Choosing login/password based receiving
[0003]  INFO mattermost:   Connecting _bot (team: F) on example.com:443
[0004]  INFO matterclient: Found version 5.9.0.5.9.0.b48f19cb0842a90f72c20c47431608a2.false
[0006]  INFO mattermost:   Connection succeeded
[0006]  INFO mattermost:   mattermost.f: joining tgs (ID: tgs mattermost.f)
[0006]  INFO mattermost:   mattermost.f: joining mm-matterbridge-test (ID: mm-matterbridge-testmattermost.f)
[0006]  INFO mattermost:   mattermost.f: joining s (ID: s mattermost.f)
[0006] DEBUG mattermost:   Choosing login/password based receiving
[0006] DEBUG mattermost:   map[string]interface {}{"team_id":"4bm9t7uyit8bbco5uidd6jhifc", "user_id":"u7ozf3uwwj83xpseqdq4dej7nh"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0xc85938]

goroutine 42 [running]:
github.com/42wim/matterbridge/bridge/mattermost.(*Bmattermost).skipMessage(0xc000319e80, 0xc0001713b0, 0x111df9b)
        /go/src/github.com/42wim/matterbridge/bridge/mattermost/helpers.go:190 +0xb8
github.com/42wim/matterbridge/bridge/mattermost.(*Bmattermost).handleMatterClient(0xc000319e80, 0xc00040d800)
        /go/src/github.com/42wim/matterbridge/bridge/mattermost/handlers.go:89 +0x21b
created by github.com/42wim/matterbridge/bridge/mattermost.(*Bmattermost).handleMatter
        /go/src/github.com/42wim/matterbridge/bridge/mattermost/handlers.go:69 +0x5a4
```

**Environment (please complete the following information):**

* OS: Ubuntu 18.04
* Matterbridge version: version: 1.14.2 e4d73b2
* Mattermost version: Version: 5.9.0

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))

**Comment by 42wim** [comment]
Thanks for reporting.
Should be fixed in master now. If possible please confirm :)

**Comment by JustDolanIt** [comment]
Tested, all good! Thanks!
