### ISSUE TITLE
[Telegram] panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by ValdikSS** [42wim/matterbridge#857]
**Describe the bug**
Matterbridge crashes with the following error:

```
panic: runtime error: slice bounds out of range

goroutine 386 [running]:
github.com/42wim/matterbridge/bridge/telegram.(*Btelegram).handleEntities(0xc000458420, 0xc0004d1e20, 0xc000628780)
        /go/src/github.com/42wim/matterbridge/bridge/telegram/handlers.go:378 +0x3b4
github.com/42wim/matterbridge/bridge/telegram.(*Btelegram).handleRecv(0xc000458420, 0xc0007f6cc0)
        /go/src/github.com/42wim/matterbridge/bridge/telegram/handlers.go:153 +0x43c
created by github.com/42wim/matterbridge/bridge/telegram.(*Btelegram).Connect
        /go/src/github.com/42wim/matterbridge/bridge/telegram/telegram.go:46 +0x376
```

**To Reproduce**
I don't know how to reproduce it. It happens once in a week.

**Environment (please complete the following information):**
- Linux
- version: 1.15.0 f06e9b5

**Comment by 42wim** [comment]
Should be fixed in #858 
You can try dev binaries with this PR in on https://bintray.com/42wim/nightly/Matterbridge/v1.15.0-11-g4762597#files
