### ISSUE TITLE
Random high CPU usage, Round 2

### ISSUE THREAD

**Issue by taoeffect** [42wim/matterbridge#89]
Followup to #68, this might be a different bug, dunno. I also don't know what commit this version was from, but it was definitely after the commit that (possibly) fixed #68.

```
SIGABRT: abort
PC=0x45ae21 m=0
goroutine 0 [idle]:
runtime.futex(0xbc13d0, 0x0, 0x0, 0x0, 0x0, 0xbc0ca0, 0x0, 0x0, 0x7fffe8cdfe60, 0x40ece2, ...)
/usr/local/go/src/runtime/sys_linux_amd64.s:387 +0x21
runtime.futexsleep(0xbc13d0, 0x0, 0xffffffffffffffff)
/usr/local/go/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0xbc13d0)
/usr/local/go/src/runtime/lock_futex.go:145 +0x82
runtime.stopm()
/usr/local/go/src/runtime/proc.go:1594 +0xad
runtime.gcstopm()
/usr/local/go/src/runtime/proc.go:1798 +0x9a
runtime.schedule()
/usr/local/go/src/runtime/proc.go:2084 +0x110
runtime.goschedImpl(0xc420186ea0)
/usr/local/go/src/runtime/proc.go:2198 +0x100
runtime.gopreempt_m(0xc420186ea0)
/usr/local/go/src/runtime/proc.go:2213 +0x36
runtime.newstack()
/usr/local/go/src/runtime/stack.go:1053 +0x318
runtime.morestack()
/usr/local/go/src/runtime/asm_amd64.s:366 +0x7f
goroutine 1 [select (no cases), 29149 minutes]:
main.main()
/home/username/gohome/src/github.com/42wim/matterbridge/matterbridge.go:59 +0x3de
goroutine 17 [syscall, 29149 minutes, locked to thread]:
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
goroutine 19 [chan receive, 29149 minutes]:
github.com/42wim/matterbridge/vendor/github.com/alecthomas/log4go.(*ConsoleLogWriter).run(0xc4200d8700, 0xb9b080, 0xc420074008)
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/github.com/alecthomas/log4go/termlog.go:33 +0x62
created by github.com/42wim/matterbridge/vendor/github.com/alecthomas/log4go.NewConsoleLogWriter
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/github.com/alecthomas/log4go/termlog.go:26 +0xbf
goroutine 20 [chan receive, 15969 minutes]:
github.com/42wim/matterbridge/gateway.(*Gateway).handleReceive(0xc420483d70, 0xc42006acc0)
/home/username/gohome/src/github.com/42wim/matterbridge/gateway/gateway.go:60 +0x87
github.com/42wim/matterbridge/gateway.New(0xc42006aae0, 0xc420097360, 0x0, 0x0)
/home/username/gohome/src/github.com/42wim/matterbridge/gateway/gateway.go:53 +0xb07
main.main.func2(0xc42006aae0, 0xc42011da10, 0x8, 0x1, 0xc42006de80, 0x2, 0x2, 0xc42006df40, 0x2, 0x2)
/home/username/gohome/src/github.com/42wim/matterbridge/matterbridge.go:53 +0x82
created by main.main
/home/username/gohome/src/github.com/42wim/matterbridge/matterbridge.go:57 +0x4c2
goroutine 21 [select, 2 minutes]:
github.com/42wim/matterbridge/vendor/github.com/nlopes/slack.(*RTM).handleEvents(0xc420150b40, 0xc420409320, 0x6fc23ac00)
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/github.com/nlopes/slack/websocket_managed_conn.go:148 +0x39
github.com/42wim/matterbridge/vendor/github.com/nlopes/slack.(*RTM).ManageConnection(0xc420150b40)
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/github.com/nlopes/slack/websocket_managed_conn.go:53 +0x1d3
created by github.com/42wim/matterbridge/bridge/slack.(*Bslack).Connect
/home/username/gohome/src/github.com/42wim/matterbridge/bridge/slack/slack.go:60 +0x61d
goroutine 22 [chan receive, 15969 minutes]:
github.com/42wim/matterbridge/bridge/slack.(*Bslack).handleSlack(0xc42012d3b0)
/home/username/gohome/src/github.com/42wim/matterbridge/bridge/slack/slack.go:150 +0x230
created by github.com/42wim/matterbridge/bridge/slack.(*Bslack).Connect
/home/username/gohome/src/github.com/42wim/matterbridge/bridge/slack/slack.go:63 +0x278
goroutine 23 [chan receive, 2 minutes]:
github.com/42wim/matterbridge/bridge/slack.(*Bslack).handleSlackClient(0xc42012d3b0, 0xc42006af60)
/home/username/gohome/src/github.com/42wim/matterbridge/bridge/slack/slack.go:161 +0xbb
created by github.com/42wim/matterbridge/bridge/slack.(*Bslack).handleSlack
/home/username/gohome/src/github.com/42wim/matterbridge/bridge/slack/slack.go:144 +0x14e
goroutine 68 [runnable]:
github.com/42wim/matterbridge/bridge/gitter.(*Bgitter).JoinChannel.func1(0xc420097450, 0xc42045bd10, 0xc420152680, 0x16)
/home/username/gohome/src/github.com/42wim/matterbridge/bridge/gitter/gitter.go:72 +0x90
created by github.com/42wim/matterbridge/bridge/gitter.(*Bgitter).JoinChannel
/home/username/gohome/src/github.com/42wim/matterbridge/bridge/gitter/gitter.go:85 +0x307
goroutine 108 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7f1de47ffcc0, 0x72, 0x5)
/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420176bc0, 0x72, 0xc420035918, 0xc42006e0a0)
/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420176bc0, 0xb9cd40, 0xc42006e0a0)
/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420176b60, 0xc420027400, 0x400, 0x400, 0x0, 0xb9cd40, 0xc42006e0a0)
/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42044a7f0, 0xc420027400, 0x400, 0x400, 0x0, 0x0, 0x0)
/usr/local/go/src/net/net.go:173 +0x70
crypto/tls.(*block).readFromUntil(0xc420337b00, 0x7f1de47bf028, 0xc42044a7f0, 0x5, 0xc42044a7f0, 0x0)
/usr/local/go/src/crypto/tls/conn.go:472 +0x91
crypto/tls.(*Conn).readRecord(0xc420452000, 0x9aed17, 0xc420452100, 0x4ed85c)
/usr/local/go/src/crypto/tls/conn.go:574 +0xc4
crypto/tls.(*Conn).Read(0xc420452000, 0xc4201b5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/usr/local/go/src/crypto/tls/conn.go:1109 +0x116
bufio.(*Reader).fill(0xc4204092c0)
/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadByte(0xc4204092c0, 0xc420455e00, 0x2, 0xc420035d38)
/usr/local/go/src/bufio/bufio.go:231 +0x51
github.com/42wim/matterbridge/vendor/golang.org/x/net/websocket.hybiFrameReaderFactory.NewFrameReader(0xc4204092c0, 0x9aed18, 0xc420192268, 0x10, 0xc420035e58)
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/golang.org/x/net/websocket/hybi.go:123 +0x5d
github.com/42wim/matterbridge/vendor/golang.org/x/net/websocket.Codec.Receive(0x9ae360, 0x9ae368, 0xc420192240, 0x8df1c0, 0xc4204644e0, 0x0, 0x0)
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/golang.org/x/net/websocket/websocket.go:314 +0xb2
github.com/42wim/matterbridge/vendor/github.com/nlopes/slack.(*RTM).receiveIncomingEvent(0xc420150b40)
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/github.com/nlopes/slack/websocket_managed_conn.go:242 +0xc4
github.com/42wim/matterbridge/vendor/github.com/nlopes/slack.(*RTM).handleIncomingEvents(0xc420150b40, 0xc420409320)
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/github.com/nlopes/slack/websocket_managed_conn.go:189 +0x57
created by github.com/42wim/matterbridge/vendor/github.com/nlopes/slack.(*RTM).ManageConnection
/home/username/gohome/src/github.com/42wim/matterbridge/vendor/github.com/nlopes/slack/websocket_managed_conn.go:50 +0x1a9
rax    0xca
rbx    0xbc0730
rcx    0xffffffffffffffff
rdx    0x0
rdi    0xbc13d0
rsi    0x0
rbp    0x7fffe8cdfe30
rsp    0x7fffe8cdfde8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x0
r13    0xc42041a680
r14    0x43ec50
r15    0xa12e60
rip    0x45ae21
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

**Comment by 42wim** [comment]
Should be fixed now, the issue happened when the connection to gitter is closed (because of bad network connection).
