### ISSUE TITLE
Discord crash

### ISSUE THREAD

**Issue by ValdikSS** [42wim/matterbridge#895]
**Describe the bug**
Matterbridge crashes inside Discord bridge

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots/debug logs**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb011f5]
goroutine 456 [running]:
 github.com/42wim/matterbridge/bridge/discord.(*Bdiscord).Send(0xc000392300, 0xc00039a700, 0x77, 0xc0003ddce0, 0x9, 0xc000f29540, 0xf, 0xc0012531a0, 0x9, 0xc000b4fbf0, ...)
         /go/src/github.com/42wim/matterbridge/bridge/discord/discord.go:273 +0x6b5
 github.com/42wim/matterbridge/gateway.(*Gateway).SendMessage(0xc000419560, 0xc00117b110, 0xc0003f4e80, 0xc000f48d80, 0x0, 0x0, 0x9, 0xc0003de800, 0x11, 0xc0003de800)
         /go/src/github.com/42wim/matterbridge/gateway/gateway.go:444 +0x6ae
 github.com/42wim/matterbridge/gateway.(*Gateway).handleMessage(0xc000419560, 0xc00117b110, 0xc0003f4e80, 0x0, 0x0, 0x0)
         /go/src/github.com/42wim/matterbridge/gateway/handlers.go:226 +0x246
 github.com/42wim/matterbridge/gateway.(*Router).handleReceive(0xc0003980f0)
         /go/src/github.com/42wim/matterbridge/gateway/router.go:143 +0x241
 created by github.com/42wim/matterbridge/gateway.(*Router).Start
         /go/src/github.com/42wim/matterbridge/gateway/router.go:96 +0x910
```

**Environment (please complete the following information):**
 - OS: Linux x86_64
 - Matterbridge version: version: 1.15.1 87788f3

**Comment by 42wim** [comment]
Already fixed in latest stable release (v1.16.0) and later
