### ISSUE TITLE
matterbridge panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by etcy** [42wim/matterbridge#916]
**Describe the bug**
Matterbridge between slack and mattermost (ver 5.15) refuses to start

**To Reproduce**
Crashes at start

**Expected behavior**
I expected Slack messages to be synced to Mattermost

**Environment (please complete the following information):**
 - OS: Centos 7
 - Matterbridge version: 1.16.0
 - In my conf, I only used webhookURL

**Screenshots/debug logs**
[root@localhost matterbridge]# /snap/matterbridge/current/bin/matterbridge -conf /opt/matterbridge/matterbridge.toml
[2019-10-04T05:37:21+09:00]  INFO main:         Running version 1.16.0
[2019-10-04T05:37:21+09:00]  INFO router:       Parsing gateway mygateway
[2019-10-04T05:37:21+09:00]  INFO router:       Starting bridge: mattermost.myteam
[2019-10-04T05:37:21+09:00]  INFO mattermost:   Connecting using webhookurl (sending)
[2019-10-04T05:37:21+09:00]  INFO mattermost:   mattermost.myteam: joining apitest (ID: apitestmattermost.myteam)
[2019-10-04T05:37:21+09:00]  INFO router:       Starting bridge: slack.testmb
[2019-10-04T05:37:21+09:00]  INFO slack:        Connecting using token
[2019-10-04T05:37:21+09:00]  INFO slack:        slack.testmb: joining testmb (ID: testmbslack.testmb)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xcae73b]

goroutine 14 [running]:
github.com/42wim/matterbridge/bridge/mattermost.(*Bmattermost).handleMatterClient(0xc42036a180, 0xc4200739e0)
        /build/matterbridge/parts/matterbridge/go/src/github.com/42wim/matterbridge/bridge/mattermost/handlers.go:86 +0x3b
created by github.com/42wim/matterbridge/bridge/mattermost.(*Bmattermost).handleMatter
        /build/matterbridge/parts/matterbridge/go/src/github.com/42wim/matterbridge/bridge/mattermost/handlers.go:69 +0x5e7

**Comment by 42wim** [comment]
Please paste your config

**Comment by 42wim** [comment]
My guess is you only configured webhookURL and not a WebhookBindAddress. 
I've fixed the panic/crash in master

**Comment by etcy** [comment]
Currently, I installed v1.16 by snap. Could someone guide me on how to use the dev binary for my case? Do i simple download the binary, rename it to matterbridge and replace the file in the /bin directory?
(Sorry for noob question)

**Comment by qaisjp** [comment]
> Do i simple download the binary, rename it to matterbridge and replace the file in the /bin directory?
I think yes, assuming that's where your current matterbridge binary lives
